src/erlang_ls_code_navigation.erl

This is one way of doing it. Not sure if it's the best way of doing it.

[#44] Resolve OTP Path dynamically

---

rebar.config

I think this would be useful for debugging purposes.

Escript log debug

---

src/erlang_ls_code_navigation.erl
src/erlang_ls_poi.erl
src/erlang_ls_tree.erl
test/erlang_ls_code_navigation_SUITE.erl

[#40] Code navigation supports funs

---

src/erlang_ls_code_navigation.erl
src/erlang_ls_poi.erl

[#76] Return the first match when there are multiple definitions

---

priv/code_navigation/src/code_navigation.erl
test/erlang_ls_code_navigation_SUITE.erl

[Closes #76] Duplicate function definition test

---

src/erlang_ls_code_navigation.erl
src/erlang_ls_poi.erl
src/erlang_ls_protocol.erl
test/erlang_ls_code_navigation_SUITE.erl

[Closes #85] Keep line and column without offset until needed

---

src/erlang_ls_client.erl
src/erlang_ls_db.erl
src/erlang_ls_definition_provider.erl
src/erlang_ls_document.erl
src/erlang_ls_protocol_impl.erl
src/erlang_ls_server.erl
src/erlang_ls_text_synchronization.erl
test/erlang_ls_proper_gen.erl
test/prop_statem.erl

[Closes #89] Rename 'buffer' and 'file' to 'document'

---

include/erlang_ls.hrl
src/erlang_ls_protocol_impl.erl
test/prop_statem.erl

[Fixes #113] Make server capabilities more explicit regarding text synchronization

---

src/erlang_ls_config.erl
src/erlang_ls_protocol_impl.erl

[#84] Move left overs for configuration setup to erlang_ls_config

---

include/erlang_ls.hrl
src/erlang_ls_completion_provider.erl
src/erlang_ls_text.erl
test/erlang_ls_completion_SUITE.erl

[Fixes #126] Handle empty lines and empty tokens

---

src/erlang_ls_code_navigation.erl

Ensure all modules are loaded on-demand if not already indexed.
Fixes #131 .

[#131] On-demand indexing for all modules

---

.travis.yml
Makefile
priv/code_navigation/include/diagnostics.hrl
priv/code_navigation/src/diagnostics.erl
src/erlang_ls_compiler_diagnostics.erl
src/erlang_ls_index.erl
src/erlang_ls_server.erl
src/erlang_ls_text_synchronization.erl
test/erlang_ls_diagnostics_SUITE.erl
test/erlang_ls_test_utils.erl
test/erlang_ls_workspace_symbol_SUITE.erl
test/prop_statem.erl

Included files are now correctly retrieved.
Fixes #135 .

[#135] Pass include dirs to compiler

---

rebar.config

A workaround until #148 is properly solved.

[#148] Drop sname from escript

---

src/erlang_ls_client.erl
src/erlang_ls_code_navigation.erl
src/erlang_ls_completion_index.erl
src/erlang_ls_completion_provider.erl
src/erlang_ls_db.erl
src/erlang_ls_hover_provider.erl
src/erlang_ls_references_index.erl
src/erlang_ls_text_synchronization.erl
src/erlang_ls_workspace_symbol_provider.erl

Simple refactoring to match OTP conventions.
Fixes #145 .

[#145] Wrap not_found message into an error tuple

---

elvis.config
src/erlang_ls_client.erl
src/erlang_ls_completion_provider.erl
src/erlang_ls_parser.erl
src/erlang_ls_range.erl
src/erlang_ls_server.erl
src/erlang_ls_text_synchronization.erl

[#143] Enforce 80 char limit via Elvis

---

priv/code_navigation/src/code_navigation.erl
src/erlang_ls_references_index.erl
test/erlang_ls_references_SUITE.erl

Enable finding references through export entries.
Fixes #162.

[#162] Find references through export entries

---

include/erlang_ls.hrl
src/erlang_ls_completion_provider.erl
src/erlang_ls_db.erl
src/erlang_ls_parser.erl
src/erlang_ls_range.erl
test/erlang_ls_completion_SUITE.erl

[#105] Return local functions, all used variables in the module and all modules indexed

---

src/erlang_ls_hover_provider.erl

[#168] Do not crash the server in case of edoc related issues

---

src/erlang_ls_parser.erl
test/erlang_ls_parser_SUITE.erl

Handle parsing errors from io:scan_erl_form/3
Fixes #170.

[#170] Handle parsing errors from io:scan_erl_form/3

---

rebar.config
src/erlang_ls.erl
src/erlang_ls_utils.erl

Escript with random node name.
Fixes #172.

[#172] Escript with random node name

---

README.md

[#172] Update README regarding connecting to an erlang_ls debug node

---

README.md
src/erlang_ls_compiler_diagnostics.erl
src/erlang_ls_config.erl
src/erlang_ls_index.erl

Add `include_dirs` configuration option to be able to specify include dirs.
#135.

[#135] include_dirs configuration option

---

src/erlang_ls_completion_provider.erl
src/erlang_ls_text.erl

[#184] Show only exported functions after colon

---

src/erlang_ls_code_navigation.erl
src/erlang_ls_completion_provider.erl
src/erlang_ls_methods.erl
src/erlang_ls_utils.erl
test/erlang_ls_completion_SUITE.erl
test/prop_statem.erl

Completion for macros and improvements in what is show in the completion based on the type of the tokens in the line. 
Fixes #104.

[#104] Completion for macros

---

src/erlang_ls_db.erl
src/erlang_ls_indexer.erl

There was an infinite loop introduced in the atomic update function.

Provide update function and fetch most recent value

---

src/erlang_ls_completion_provider.erl
test/erlang_ls_completion_SUITE.erl

Restrict completion of modules based on prefix.
Fixes #203.

[#203] Filter by prefix

---

src/erlang_ls_completion_provider.erl
src/erlang_ls_indexer.erl
test/erlang_ls_completion_SUITE.erl

Complete only with arity for named funs
Fixes #200.

[#200] Complete only with arity for named funs

---

src/erlang_ls_methods.erl
test/prop_statem.erl

[#211] Fix format of saveOptions

---

src/erlang_ls_methods.erl
test/prop_statem.erl

[#213] Implement stub for workspace/didChangeWatchedFiles

---

src/erlang_ls_client.erl
src/erlang_ls_config.erl
src/erlang_ls_hover_provider.erl
src/erlang_ls_methods.erl

[#215] Do not assume markdown

---

README.md

I didn't manage to connect to the server with these instructions, yet, but I am opening the PR so we can see and tweak them.
Requires #16 .

[#14] Add IntelliJ instructions

---

README.md
rebar.config
src/els_utils.erl
src/erlang_ls.app.src
src/erlang_ls.erl

Write logs for all projects under a single root dir.
Fixes #147.

[#147] Write logs under single location

---

.travis.yml
Makefile

Default target builds escript.
Fixes #220.

[#220] Default target builds escript

---

README.md

[#220] Update README with new make targets

---

src/els_code_navigation.erl
src/els_completion_provider.erl
src/els_indexer.erl
src/els_utils.erl

Implement folding over files manually and skip symlinks
Fixes #102.

[#102] Implement folding over files manually and skip symlinks

---

src/els_utils.erl

Check if top level directory is symlink
Improves #102.

[#102] Check if top level directory is symlink

---

README.md

[#227] Add VSCode setup

---

elvis.config
src/els_dodger.erl
src/els_parser.erl

[#235] Fork the dodger

---

src/els_client.erl
src/els_hover_provider.erl

Fetch the hover content format.
Fixes #255.

[#255] Fetch the hover content format

---

README.md

[257] clearer language

---

src/els_client.erl

Should not change any functionality, just a deduplication of much of the handle_call clauses. Parameter construction is still a little unwieldy, and the Method lookup could be improved, but this seems a step in the right direction. 
Fixes #144.

Condense handle_call/3 and reduce duplication in parameter handling

---

src/els_completion_provider.erl
src/els_parser.erl
src/els_range.erl
test/els_completion_SUITE.erl

[#92] Add code completion for record names

---

README.md

Missing instructions Emacs
Fixes #204.

[#204] Missing instructions Emacs

---

include/erlang_ls.hrl
src/els_client.erl
src/els_document_highlight_provider.erl
src/els_methods.erl
src/els_provider.erl
src/els_references_provider.erl
test/els_document_highlight_SUITE.erl
test/prop_statem.erl

Adds support for document highlighting.
This commit introduces the feature.  There will be follow-up ones to improve the quality of the highlighting provided.
Fixes #232 .

[#232] Introduce document highlighting

---

include/erlang_ls.hrl
src/els_code_navigation.erl
src/els_completion_provider.erl
src/els_definition_provider.erl
src/els_document.erl
src/els_parser.erl
src/els_poi.erl
src/els_range.erl
test/els_completion_SUITE.erl

Completion returns function/arity when in export list.
Fixes #196.

[#196] Completion returns function/arity when in export list

---

README.md

Introduce sections in Emacs configuration.
Fixes #155.

[#155] Describe how to configure helm-lsp for workspace symbols

---

README.md

[#204] Add link to exec-path-from-shell Emacs package

---

src/els_completion_provider.erl

Handle multiple exports sections
Related to #196.

[#196] Handle multiple exports sections

---

src/els_client.erl
src/els_methods.erl
src/els_server.erl
src/els_stdio.erl
src/els_tcp.erl
src/els_text_synchronization.erl
test/els_diagnostics_SUITE.erl
test/prop_statem.erl

[#286] Do not pass els_server's PID around

---

priv/code_navigation/src/behaviour_a.erl
src/els_methods.erl
src/els_parser.erl

Don't assume more tokens and/or dot.
Fixes #288.

[#288] Don't assume more tokens and/or dot

---

README.md

[#299] We require emacs-lsp 6.2

---

README.md

[#69] Add notes about projects in Emacs

---

src/els_db.erl
src/els_indexer.erl
test/els_document_highlight_SUITE.erl

This is one way to solve things. Please advise if you think we should do something else.
Fixes #302 .

[#302] Solve flakyness of els_document_highlight_SUITE

---

elvis.config
src/els_config.erl
src/els_elvis_diagnostics.erl
src/els_parser.erl

I think @alanz raised this in one of his PRs and I believe it makes sense.
Fixes #292 .

[#292] Stricter operator_spaces checks for Elvis

---

priv/code_navigation/include/code_navigation.hrl
src/els_completion_provider.erl
src/els_methods.erl
src/els_parser.erl
test/els_completion_SUITE.erl
test/prop_statem.erl

Implements completion for record fields.
Fixes #93.

[#93] Record fields completion 

---

src/els_db.erl

Avoid timeouts while #309 is properly investigated.

[#309] Increase DB wait_for_tables timeout to 20s until the root cause is identified

---

src/els_db.erl
src/els_db_table.erl

[#317] Crash on table creation errors

---

src/els_code_navigation.erl
src/els_completion_provider.erl
src/els_db.erl
src/els_dt_document.erl
src/els_dt_document_index.erl
src/els_indexer.erl
src/els_utils.erl
src/els_workspace_symbol_provider.erl
test/els_references_SUITE.erl

Introduce module table for mapping module/header name to uri.
Fixes #312.

[#312] Introduce module table for mapping module/header name to uri

---

src/els_utils.erl
test/els_indexer_SUITE.erl

Check that a file is a dir, don't assume it is.
Fixes #331.

[#331] Check the file is a dir

---

src/els_methods.erl
src/els_text_synchronization.erl
test/els_test_utils.erl

[#327] Generate diagnostics when a file is opened

---

src/els_methods.erl
test/prop_statem.erl

[#341] Gracefully handle requests during initialization

---

README.md
elvis.config
include/erlang_ls.hrl
src/els_client.erl
src/els_folding_range_provider.erl
src/els_methods.erl
src/els_parser.erl
src/els_poi.erl
src/els_provider.erl
src/els_server.erl
test/els_foldingrange_SUITE.erl
test/prop_statem.erl

The folding provider allows to collapse/expand parts of the code. Right now this is implemented only for functions.
Fixes #359 .

[#359] Folding provider

---

src/els_db.erl
src/els_utils.erl

Stop DB properly before shutdown.
Fixes #337.

[#337] Stop DB properly

---

src/els_db.erl
src/els_dt_references.erl
test/els_references_SUITE.erl

Delete only references with the provided URI
Fixes #375.

[#375] Delete only references with the provided URI

---

README.md

Add elisp syntax highlighting to README.md

---

priv/code_navigation/src/code_navigation_extra.erl
src/els_hover_provider.erl
test/els_definition_SUITE.erl
test/els_hover_SUITE.erl

Generate hover information for local functions too

---

src/els_formatting_provider.erl

Remove excessive logging from els_formatting_provider

Remove excessive logging from els_formatting_provider

---

README.md

Add instructions on how to setup Sublime Text 3 to connect to Erlang LS.
Fixes #398 .

[#398] Add instructions for Sublime Text 3

---

.editorconfig

See https://editorconfig.org/
For emacs
(package-install 'editorconfig)
(editorconfig-mode 1)

Add .editorconfig file, configured as per contribution guidelines

---

.gitignore
Makefile

[#422] Build edoc

---

README.md
priv/code_navigation/erlang_ls.config
priv/code_navigation/src/diagnostics_macros.erl
src/els_compiler_diagnostics.erl
src/els_config.erl
test/els_diagnostics_SUITE.erl
test/els_test_utils.erl

[#424] Add support for custom macros

---

README.md
misc/dotemacs

[#402] Move Emacs config to separate file, add troubleshooting instructions

---

src/els_db.erl

[#318] Introduce schema versioning

---

src/els_utils.erl

Use absolute paths, normalised to remove duplicate path separators and embedded `.` or `..` parts.
This is particularly important on vscode when doing "go to definition", if the path has `..` in it, the file opens, but none of the indexing lookup works.
Fixes #408 .

[#408] Normalize the paths in the search directories

---

src/els_utils.erl

Fix nit from #432

---

src/els_app.erl

[#442] Elvis must not use stdio

---

priv/code_navigation/include/parse_transform.hrl
priv/code_navigation/src/diagnostics_parse_transform.erl
priv/code_navigation/src/diagnostics_parse_transform_usage.erl
priv/code_navigation/src/diagnostics_parse_transform_usage_included.erl
src/els_compiler_diagnostics.erl
src/els_db.erl
src/els_parser.erl
src/els_range.erl
test/els_diagnostics_SUITE.erl
test/els_test_utils.erl

[#416] Add support for parse transforms

---

README.md

[#453] Fix path to misc/dotemacs

---

elvis.config
src/els_client.erl
src/els_methods.erl
src/els_server.erl
test/prop_statem.erl

[#448] Ignore $/ notifications and requests

---

src/els_text_synchronization.erl
test/els_diagnostics_SUITE.erl

Do not try and code reload sticky modules

---

src/els_indexer.erl
src/els_range.erl
src/els_references_provider.erl
test/els_definition_SUITE.erl
test/els_references_SUITE.erl

Implements the possibility to find references for a record. 
Fixes #465

[#465] Find record references

---

src/els_utils.erl
src/erlang_ls.erl

Exposes lager's log level to the CLI.
Fixes #430.

[#430] Expose logging level

---

README.md
src/els_utils.erl
src/erlang_ls.erl

[#430] Simplify and document logging

---

src/els_db.erl

[#467] Bump schema version, to ensure record references are indexed

---

.gitpod.yml
README.md

Theia IDE documentation and GitPod configuration
Fixes #470.

[#470] Theia IDE documentation and GitPod configuration

---

src/els_db.erl
src/els_dialyzer_diagnostics.erl

Dialyzer diagnostics failure.
Fixes #487.

[#487] Dialyzer diagnostics failure

---

src/els_app.erl
src/els_sup.erl

* Mark els_providers_sup as supervisor
* Include els_server in the supervision tree
Fixes #490 .

490 fix supervision strategy

---

priv/code_navigation/src/code_navigation.erl
src/els_text.erl
test/els_completion_SUITE.erl
test/els_foldingrange_SUITE.erl

Handle errors when using erl_scan.
Fixes #495.

[#495] Handle errors when using erl_scan

---

src/els_code_navigation.erl
src/els_indexer.erl
src/els_parser.erl
src/els_range.erl
src/els_references_provider.erl
test/els_definition_SUITE.erl
test/els_references_SUITE.erl

Find references for macros.
Fixes #421.

[#421] Find references for macros

---

src/erlang_ls.erl
test/erlang_ls_SUITE.erl

Erlang LS escript was previously not covered by any tests so added these.
No known issue number to link.

Add basic testing for erlang ls escript

---

src/els_parser.erl
src/els_range.erl
src/els_references_provider.erl
test/els_definition_SUITE.erl
test/els_references_SUITE.erl

Find references for module.
Fixes #497  .

497 references for module

---

src/els_sup.erl

Fix logic of when to restrict access to stdio
Related #518.

[#518] Fix logic of when to restrict access to stdio

---

src/els_execute_command_provider.erl

Reword comment.

---

.github/SUPPORT.md

[#72] Add SUPPORT.md

---

src/els_hover_provider.erl

EEP48 provides documentation for erlang application/modules.
OTP-23 implements EEP48 and provide the doc info if available.
If user uses an OTP version that provides the functionality and the
doc_chunks are available use that by default and if not fallback to
fetching the docs from src via 'erlang_ls' own implementation.
This is a foundation for further work where we should write an
doc_chunk to markdown renderer, when markdown available in the client.

Use OTP's get_doc if available

---

test/els_definition_SUITE.erl
test/els_diagnostics_SUITE.erl
test/els_implementation_SUITE.erl
test/els_test_utils.erl
test/els_text_edit_SUITE.erl

No functional changes, simply removing the duplication in the file.
This helper module needs some serious love, this is the first part.
Fixes #546 .

[#546] DRY els_test_utils module

---

README.md

553 move docs to website

---

.gitpod.yml

[#562] Bump VSCode extension in GitPod file

---

.gitpod.yml

[#562] Include content hash for VSCode extension

---

.github/workflows/build.yml
rebar.config
rebar.config.script
src/els_hover_provider.erl

[#567] Run all checks in CI

---

README.md

Adds some clarification to a place where I got tripped up.

Clarify path to default config file

---

src/erlang_ls.app.src

Enable logging by default.
Related to #560.

[#560] Enable logging by default

---

.github/workflows/build.yml
test/els_hover_SUITE.erl

[#550] Add OTP 23 pipeline

---

.github/workflows/build.yml
src/els_code_action_provider.erl
src/els_compiler_diagnostics.erl
src/els_completion_provider.erl
src/els_config.erl
src/els_dialyzer_diagnostics.erl
src/els_document_symbol_provider.erl
src/els_execute_command_provider.erl
src/els_hover_provider.erl
src/els_indexer.erl
src/els_io_string.erl
src/els_methods.erl
src/els_stdio_client.erl
src/els_text.erl
src/els_text_synchronization.erl
test/els_indexer_SUITE.erl
test/els_indexing_SUITE.erl
test/els_proper_gen.erl
test/els_rebar3_release_SUITE.erl
test/els_test_utils.erl

Use unicode module instead of `[io]list_to_binary/1` and `binary_to_list/1`
Fixes #306.

[#306] Use unicode module

---

src/els_providers_sup.erl

[#595] Allow a provider restart every 5 seconds

---

src/els_uri.erl
test/els_references_SUITE.erl

Fix URI handling bug.
Fixes #593.

[#593] Fix URI handling bug

---

README.md
src/erlang_ls.erl

List possible transport options in README
Fixes #476.

[#476] list possible transport options

---

src/els_client.erl
src/els_xref_diagnostics.erl

[#646] Do not crash on not existing URIs, correctly handle server requests

---

.github/CONTRIBUTING.md

Since the amount of collaborators is growing, I believe is good to write down some guidelines for reviewers, too. These are simply my own suggestions, so feel free to argue against them, if you believe they are not what we want.

Add code review guidelines

---

src/els_client.erl
src/els_general_provider.erl
src/els_methods.erl
test/prop_statem.erl

Restore #634 which, in its first implementation, contained a bug. Add tests for initialized.
Fixes #622 .

[#622] Fix initialized bug

---

misc/dotemacs

[#677] Enable sideline by default

---

src/els_diagnostics.erl

[#676] Include module name in Diagnostics progress reports

---

src/els_db.erl
src/els_work_done_progress.erl

[#675] progress report while waiting for tables

---

rebar.config
rebar.config.script

[#693] Bump coveralls plugin, update config

---

specs/runtime_node.md

[#723] First draft of a runtime node protocol spec

---

src/els_parser.erl
test/els_parser_SUITE.erl

Handle `-define(_, smth).`. Fixes #727

---

src/els_xref_diagnostics.erl
test/els_diagnostics_SUITE.erl

[#733] Disable xref diagnostics by default

---

src/els_config.erl
src/els_utils.erl

This reverts commit 2071faf5dbef89b355afad940febee40fb96a348.
Fixes #732 .

Revert "Add all subdirs to search path"

---

.github/CONTRIBUTING.md

[#711] Mention rebar3 templates in the contributing guidelines

---

rebar.config

[#737] Remove rebar integration until stable

---

src/els_sup.erl

[#712] Add start log, including version

---

src/els_sup.erl

[#749] Add support for I/O getopts request

---

src/els_general_provider.erl
src/els_hover_provider.erl

[#751] Do not crash when fetching doc chunks for escriptized modules

---

src/els_compiler_diagnostics.erl

[#745] Use compile options when available

---

src/els_diagnostics_utils.erl

Remove spurious call to els_dt_document:lookup/1

---

.github/workflows/build.yml

Fixed path to PLT file generated by rebar3

CI: fix path to PLT cache

---

src/els_dap_general_provider.erl

Otherwise it does not use the features.

[DAP] advertise capabilities for vscode

---

src/els_completion_provider.erl

Not all LS clients send `context` as this is not required by the specs. So instead of failing to return any completions it will just assume manually triggered completion.
In addition it allows completion after just plain trigger character even when invoked manually.

Assume invoked trigger kind

---

src/els_compiler_diagnostics.erl
src/els_dialyzer_diagnostics.erl
src/els_utils.erl

[#785] Pass custom macros to Dialyzer

---

misc/dotemacs

[#786] Remove obsolete company-lsp instructions

---

README.md

Add links to the requirements in the readme.

Update readme, add links to requirements

---

SPAWNFEST.md
src/els_dap_general_provider.erl
src/els_dap_protocol.erl
src/els_dap_server.erl
src/els_distribution_server.erl

And stub out some more functions.
`stepOut` currently does the same as `step`.

[DAP] add ability to launch in integrated terminal

---

src/els_hover_provider.erl

I recently started using erlang_ls and found an itch with it that I needed to scratch.
Before this change, any els hover request used only the path of the running VM to find the doc chunks. This made using `otp_path` to point out which OTP version to use not work for hover requests.
With this change, the hover provider now looks using els db for the .beam and .chunk file in the local filesystem.
I'm not sure how to add tests for this, any suggestions? I looked around but it seems like very few other testcases change the `otp_path`.

Make doc chunk search use els db instead of code path

---

src/els_parser.erl
test/els_parser_SUITE.erl

[#815] Record definitions cannot be navigated from type specs

---

src/els_parser.erl
test/els_parser_SUITE.erl

[#818] Allow navigation to user defined types and records from within types

---

priv/code_navigation/include/rename.hrl
priv/code_navigation/src/rename_usage1.erl
priv/code_navigation/src/rename_usage2.erl
src/els_rename_provider.erl
test/els_rename_SUITE.erl
test/els_test_utils.erl

[#825] Add support for renaming macros

---

src/els_document_highlight_provider.erl
src/els_rename_provider.erl
test/els_document_highlight_SUITE.erl

[#827] Enable Document Highlighting for most POIs

---

priv/code_navigation/src/completion.erl
priv/code_navigation/src/completion_caller.erl
src/els_completion_provider.erl
test/els_completion_SUITE.erl
test/els_test_utils.erl

[#790] Only complete with arity for remote applications

---

priv/code_navigation/src/code_navigation_types.erl
src/els_parser.erl
src/els_range.erl
test/els_completion_SUITE.erl
test/els_definition_SUITE.erl
test/els_document_highlight_SUITE.erl
test/els_references_SUITE.erl
test/els_rename_SUITE.erl

Fixes a bunch of problems when it comes to ranges, there are still more left. I'll try to get a PR for those as well.

Fix macro entry opaque ranges

---

src/els_methods.erl

[#674] Include OTP version on startup

---

elvis.config
priv/code_navigation/src/diagnostics_parse_transform_deps_a.erl
priv/code_navigation/src/diagnostics_parse_transform_deps_b.erl
priv/code_navigation/src/diagnostics_parse_transform_deps_c.erl
src/els_diagnostics_utils.erl
test/els_diagnostics_SUITE.erl
test/els_test_utils.erl

[#799] Consider parse transform runtime deps as deps

---

src/els_dap_general_provider.erl
src/els_dap_rpc.erl
src/els_dap_sup.erl

- start els_config and initialize it during DAP startup
- add handler and capability for setFunctionBreakpoints

Fix DAP startup and add function breakpoints

---

src/els_dap_general_provider.erl

This implements the scopes and variables request for showing variables in the vscode UI

[dap] implement protocol for showing variables

---

src/els_unused_macros_diagnostics.erl

[#886] Limit unused macro detection to .erl files

---

src/els_dap_general_provider.erl

- support improper lists
- fix sorting of map assocs (show key first)

[dap] support improper lists for showing variables

---

rebar.config
src/els_dap_agent.erl
src/els_dap_general_provider.erl
src/els_dap_rpc.erl

- implementation for evaluate callback:
- get values when overing over variables
- support expressions for watch and repl
- complete stack frames

[dap] implement evaluate and stacktrace callbacks for dap

---

rebar.config

[#894] Fetch rebar3_bsp from git, since it's not yet published to Hex

---

.github/workflows/build.yml

There are still a few issues with the pipeline:
* The pre-compile hook fails
* rebar3 detects the error, but terminates with a zero status code
Fixes #305 .

[#305] Add Windows CI pipeline

---

apps/els_core/src/els_core.app.src
apps/els_lsp/src/els_lsp.app.src
erlang_ls.config.sample

[#895] Follow ups from code review

---

Makefile

Add dap to 
```
make all
make install
```

add dap to make targets

---

apps/els_core/src/els_distribution_server.erl
apps/els_dap/src/els_dap_general_provider.erl

This makes the connection from the DAP node to the project node hidden

[dap] make connection to project node hidden

---

apps/els_lsp/src/els_snippets_server.erl

[#933] Fix support for snippets

---

apps/els_lsp/priv/code_navigation/src/code_lens_function_references.erl
apps/els_lsp/src/els_code_lens.erl
apps/els_lsp/src/els_code_lens_function_references.erl
apps/els_lsp/src/els_code_lens_server_info.erl
apps/els_lsp/src/els_code_lens_suggest_spec.erl
apps/els_lsp/test/els_code_lens_SUITE.erl
apps/els_lsp/test/els_completion_SUITE.erl
apps/els_lsp/test/els_initialization_SUITE.erl
apps/els_lsp/test/els_test_utils.erl

[#946] Add code lens to show function references

---

apps/els_lsp/src/els_indexing.erl

The problem is described in the referenced issue. The way it is solved is by avoiding fullscan `els_dt_references:delete_by_uri` if the URI is not yet in the index (which is always the case when erlang_ls is just started and does initial indexing).
It opens a small window for race conditions (if you start editing the file same time it's indexed by background indexer), but since re-indexing is executed pretty often, incorrect data from race condition will be overwritten very quickly after a few keystrokes.
The ideal solution would still be some kind of reverse index I guess (from URI to the list of references), because we still are doing this fullscan quite often when editing the document so it's reindexed. But, given that `els_dt_references` is now the heaviest table, it might be quite …

Only match_delete from references table when the file is already in index

---

apps/els_lsp/src/els_code_navigation.erl

Fix invalid log formatting in els_code_navigation

---

apps/els_lsp/priv/code_navigation/src/rename_function.erl
apps/els_lsp/priv/code_navigation/src/rename_function_import.erl
apps/els_lsp/src/els_dt_references.erl
apps/els_lsp/src/els_indexing.erl
apps/els_lsp/src/els_rename_provider.erl
apps/els_lsp/test/els_references_SUITE.erl
apps/els_lsp/test/els_rename_SUITE.erl
apps/els_lsp/test/els_test_utils.erl

Add support for renaming functions

Add support for renaming functions

---

apps/els_lsp/src/els_rename_provider.erl
apps/els_lsp/test/els_rename_SUITE.erl

Add support for renaming function from function clause

Add support for renaming function from function clause

---

apps/els_lsp/src/els_definition_provider.erl

This fixes an issue where defintion could not be found due to POIs overlapping and the "interesting" POI wasn't the first in the list of POIs.
With this change we will try each POI until we get a match instead of just trying the first POI in the list.

Try to goto definition for each POI at pos until there's a match

---

apps/els_core/include/els_core.hrl
apps/els_lsp/priv/code_navigation/src/completion_attributes.erl
apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/src/els_general_provider.erl
apps/els_lsp/test/els_completion_SUITE.erl
apps/els_lsp/test/els_test_utils.erl

Add completion for most module attributes.
Also add nice context aware completions for
```
-behaviour(<tab>
-include("<tab>
-include_lib("<tab>
```
Try it out!

Add completions for attributes

---

apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/src/els_general_provider.erl
apps/els_lsp/test/els_completion_SUITE.erl

Add " as a trigger character.
Use it for include/include_lib completion.
Don't add quotes in include snippets.

Add " as a trigger character 

---

apps/els_lsp/priv/code_navigation/src/code_navigation.erl
apps/els_lsp/src/els_code_navigation.erl
apps/els_lsp/test/els_definition_SUITE.erl

Goto type definition from export_type entry
Fixes #929 .

[#929] Goto type definition from export_type entry

---

apps/els_lsp/src/els_background_job.erl

Clear stalled indicator on termination
Fixes #981 .

#981: Clear stalled indicator on termination

---

apps/els_lsp/src/els_compiler_diagnostics.erl
apps/els_lsp/src/els_diagnostics_utils.erl
apps/els_lsp/src/els_dialyzer_diagnostics.erl
apps/els_lsp/test/els_server_SUITE.erl

Dialyzer diagnostics will now use the same range calculation as compiler diagnostics.
Follow up to suggestion in PR of #1006

Make more exact dialyzer diagnostics by utilizing column number

---

apps/els_dap/src/els_dap_general_provider.erl

If "projectnode" property is a short name, use_long_names = true expands the node name with @hostname.domainname.
This way "projectnode" can be a short name ( ${workspaceFolderBasename} in VSCODE for example) so launch.json can be generic for a repository as no local node name setting is required.
Fixes # .

Add support for using long names in dap for project node

---

apps/els_lsp/priv/code_navigation/src/rename_type.erl
apps/els_lsp/src/els_rename_provider.erl
apps/els_lsp/test/els_rename_SUITE.erl
apps/els_lsp/test/els_test_utils.erl

Add support for renaming types

Add support for renaming types

---

apps/els_lsp/priv/code_navigation/src/hover_macro.erl
apps/els_lsp/src/els_docs.erl
apps/els_lsp/test/els_hover_SUITE.erl

Fix docs for macro with arguments

---

apps/els_lsp/src/els_background_job.erl
apps/els_lsp/src/els_compiler_diagnostics.erl

[#1049] Lower log level for background jobs and compile info/options to DEBUG

---

apps/els_lsp/src/els_unused_includes_diagnostics.erl

By considering only those POIs relevant for this diagnostic, e.g. POIs which MAY potentially be defined in headers. This often significantly cuts number of POIs to iterate over which directly speeds up the diagnostic.

Improve unused includes diagnostic runtime

---

.github/workflows/build.yml
rebar.config

[#240] Publish escripts

---

.github/CONTRIBUTING.md

[#625] Add guidelines on encoding strings

---

apps/els_core/src/els_config.erl
apps/els_core/src/els_provider.erl
apps/els_lsp/src/els_bsp_client.erl
apps/els_lsp/src/els_bsp_provider.erl
apps/els_lsp/src/els_formatting_provider.erl
apps/els_lsp/src/els_general_provider.erl
apps/els_lsp/src/els_indexing.erl
apps/els_lsp/test/els_indexing_SUITE.erl

Started adding BSP support, this is an RFC.

BSP support

---

apps/els_core/src/els_client.erl
apps/els_core/src/els_protocol.erl
apps/els_lsp/src/els_server.erl

[#1107] Shutdown request does not include parameters

---

apps/els_lsp/priv/code_navigation/src/diagnostics_parse_transform_error.erl
apps/els_lsp/priv/code_navigation/src/my_parse_transform.erl
apps/els_lsp/src/els_compiler_diagnostics.erl
apps/els_lsp/test/els_diagnostics_SUITE.erl

[1140] Do not include error description in code

---

apps/els_lsp/src/els_docs.erl

[#1143] Lower docs log message level to DEBUG

---

apps/els_lsp/src/erlang_ls.erl

[#1149] Exit with 0 on --version

---

apps/els_core/src/els_config.erl

This allows for a a global config which can be overridden by project specific configs.
As suggested by @alanz: https://github.com/erlang-ls/erlang_ls/pull/380#pullrequestreview-341787386

Augment local config onto global config

---

apps/els_core/src/els_client.erl
apps/els_lsp/src/els_completion_provider.erl

Completion without snippets

---

apps/els_lsp/src/els_rename_provider.erl
apps/els_lsp/test/els_rename_SUITE.erl

Support renaming function when standing on spec

---

apps/els_core/include/els_core.hrl
apps/els_core/src/els_protocol.erl
apps/els_core/src/els_utils.erl
apps/els_lsp/priv/code_navigation/src/code_action.erl
apps/els_lsp/src/els_code_action_provider.erl
apps/els_lsp/src/els_execute_command_provider.erl
apps/els_lsp/test/els_code_action_SUITE.erl
apps/els_lsp/test/els_completion_SUITE.erl

Implement a couple of new code actions:
* If function is unused, provide action to export it
* If variable is unbound, provide action to fix spelling
* If module name doesn't match filename, provide action to fix it
This also includes refactoring of `els_code_action_provider` and fixing
the unused variable code action that didn't work properly.
Fixes #1207.
Fixes #1210.

Implement new code actions

---

rebar.config

See https://github.com/yakaz/yamerl/pull/54 for context.

Bump yamerl

---

apps/els_lsp/priv/code_navigation/src/code_navigation.app.src
apps/els_lsp/src/els_edoc_diagnostics.erl
apps/els_lsp/test/els_diagnostics_SUITE.erl

Only run EDoc diagnostics on .erl files

---

Makefile
README.md

Allow user to provide custom PREFIX
Example:
```bash
$ PREFIX=~/.local make install
```

Allow user to provide custom PREFIX

---

apps/els_core/src/els_uri.erl
apps/els_core/src/els_utils.erl
apps/els_lsp/test/els_proper_gen.erl
apps/els_lsp/test/prop_statem.erl

Get tmp system dir in a portable way during tests

---

apps/els_lsp/src/els_code_action_provider.erl
apps/els_lsp/src/els_code_actions.erl

Fixes review comments in #1212.

Code actions refactoring to fix review comments

---

apps/els_lsp/src/els_scope.erl

Only follow includes for hrl files

---

apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/test/els_completion_SUITE.erl

Add completion support for [feature](https://www.erlang.org/doc/reference_manual/features.html) related macros and attributes.

Add completion support for features

---

apps/els_lsp/src/els_unused_includes_diagnostics.erl

While identifying unused includes, the current implementation performs
a go-to-definition operation for all POIs within a document, even if
all the .hrl candidates have already been excluded.
This change stops the iteration as soon as no candidates are present.
The whole detection algorithm could probably be revisited (it would be
good to check if this problem has been tackled in literature), but for
now this optimization will lower the execution time for "unused
includes" diagnostics and reduce the stress on the language server,
especially for big modules.
As an example, this optimization reduces the computing time for
"unused includes" diagnostics for the `els_parser.erl` module from ~1s
to ~200ms.

Optimize unused includes detection by avoiding unnecessary work

---

apps/els_lsp/src/els_call_hierarchy_provider.erl

`els_dt_document:wrapping_functions/2` can return zero or one items in a list.
Explicitly deal with both options.
See https://github.com/erlang-ls/erlang_ls/pull/1096#discussion_r718748583

Make "callHierarchy/incomingCalls" more resilient

---

apps/els_dap/src/els_dap_general_provider.erl

Tries to normalize source paths obtained by the module.

[dap] normalize paths in source field

---

apps/els_lsp/src/els_methods.erl

Only do that in case of requests.

Do not respond to notifications in case of internal errors

---

apps/els_lsp/src/els_parser.erl
apps/els_lsp/test/els_parser_SUITE.erl

Add support for record index in els_parser.
Fixes #1391.

[#1391] Add support for record index in els_parser

---

apps/els_core/src/els_config.erl

fix error when using "code_path_extra_dirs" in windows

---

apps/els_lsp/src/els_completion_provider.erl

* Use els_dt_document:find_candidates/1 to avoid checking all modules
* Check if prefix matches before looking for callback POIs

Improve performance when completing behaviours

---

apps/els_lsp/test/els_docs_SUITE.erl

Suite keeps failing on CI, disable it until it has been resolved.

Disable els_docs_SUITE

---

apps/els_core/src/els_config.erl
apps/els_lsp/src/els_methods.erl
apps/els_lsp/test/els_diagnostics_SUITE.erl

Expand environment variables in config file.
Fixes #1121 .

[#1121] Expand enviroment variables in config file

---

apps/els_lsp/src/els_completion_provider.erl

Completion of module macro

---

apps/els_lsp/src/els_arg.erl
apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/src/els_dt_signatures.erl
apps/els_lsp/src/els_indexing.erl
apps/els_lsp/src/els_inlay_hint_provider.erl

Store spec args in signature index for better performance

---

apps/els_lsp/src/els_formatting_provider.erl

Example:
```
formatting:
files:
- "apps/**"
exclude_files:
- "apps/**/generated_file.erl"
```

Add config option to include / exclude files for formatting.

---

apps/els_lsp/priv/code_navigation/src/completion_more.erl
apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/test/els_completion_SUITE.erl

Add some nicer completions for keywords and list/map comprehensions.

More completions

---

apps/els_lsp/src/els_formatting_provider.erl

Example:
```
formatting:
width: 80
```

Add possiblity to configure formatting width

---

apps/els_lsp/src/els_docs.erl
apps/els_lsp/src/els_eep48_docs.erl
apps/els_lsp/test/els_completion_SUITE.erl
apps/els_lsp/test/els_hover_SUITE.erl

Add hover docs support for new OTP 27 style docs.

Support OTP 27 style docs

---

apps/els_lsp/src/els_code_actions.erl
apps/els_lsp/src/els_completion_provider.erl
apps/els_lsp/src/els_dt_document.erl
apps/els_lsp/test/els_completion_SUITE.erl

Also fixes completion for OTP behaviours

Add OTP support in "Add include_lib" action
