erlang-ls/erlang_ls

rebar.config, rebar.lock
Hello 
I cannnot compile this project, Because lager version is old.
```
rebar3 shell
===> Verifying dependencies...
===> Compiling lager
/Users/takuya.hirata/erlang_ls/_build/default/lib/lager/src/lager_util.erl: redefining predefined macro 'FUNCTION_NAME'
===> Compiling _build/default/lib/lager/src/lager_util.erl failed
_build/default/lib/lager/src/lager_util.erl:none: redefining predefined macro 'FUNCTION_NAME'
```
So upgrade lager version.
please checkout.
thank you.
=> upgrade lager version

src/erlang_ls_server.erl
#19. This enables restarting the server from an LSP client (e.g. in `lsp-mode` with the command `lsp-workspace-restart`).
=> [#19] Basic implementation of shutdown and exit requests

src/erlang_ls_code_navigation.erl, src/erlang_ls_poi.erl, src/erlang_ls_tree.erl
I tried indexing all of OTP with the changes in this branch and the only mesages printed are related to the missing spec locations.
=> Avoid exceptions when analyzing the syntax tree

src/erlang_ls_completion_provider.erl, src/erlang_ls_document.erl, src/erlang_ls_text.erl
* Move text manipulation functions to a separate module
* Use OTP library functions instead of custom pattern matching.
Fixes #116 .
=> [#116] Refactor extraction of last token from text

src/erlang_ls_parser.erl, src/erlang_ls_tree.erl, test/erlang_ls_parser_SUITE.erl
Handle the case where a function spec has more than one clause and a test to avoid regression.
Fixes #120
=> [Fixes #120] Handle more than one clause in the function spec

include/erlang_ls.hrl, src/erlang_ls_client.erl, src/erlang_ls_document_symbol_provider.erl, src/erlang_ls_protocol_impl.erl, src/erlang_ls_provider.erl, test/erlang_ls_document_symbol_SUITE.erl, test/prop_statem.erl
Add support for the document symbol provider. This makes it possible, in Emacs, to use the `imenu` command to navigate to functions.
Fixes #123 .
=> [#123] Add support for textDocument/documentSymbol

src/erlang_ls_code_navigation.erl, src/erlang_ls_completion_provider.erl, src/erlang_ls_document.erl, src/erlang_ls_document_symbol_provider.erl, src/erlang_ls_poi.erl, src/erlang_ls_references_index.erl, src/erlang_ls_tree.erl
* Remove the pointless `type` field from the POI map.
* Split the `info` field into separate `kind` and `data`
* Be able to retrieve only a subset of POIs
Fixes #125  .
=> [#125] Cleanup the POI data structure, add points_of_interest/2 API.

src/erlang_ls_code_navigation.erl, src/erlang_ls_definition_provider.erl, src/erlang_ls_document.erl, src/erlang_ls_index.erl, src/erlang_ls_poi.erl, src/erlang_ls_text_synchronization.erl, src/erlang_ls_tree.erl
The code navigation section was not using the DB and it was partially re-implementing indexing.
This PR heavily refactors the code navigation part to:
* use `uri()` directly instead of converting from/to filenames un-necessarily
* move path management to the indexer, where it belongs to
* remove un-necessary match functions acting on the tree
* make the code navigation code uniform in all clauses
* index also `.hrl` files
This change *should* not change anything in terms of functionality, hence the test suite is untouched.
Fixes #131 .
=> [#131] The definition provider uses indexed data for code navigation

src/erlang_ls_client.erl, src/erlang_ls_methods.erl, src/erlang_ls_protocol.erl, src/erlang_ls_protocol_impl.erl, src/erlang_ls_server.erl, src/erlang_ls_utils.erl, test/prop_statem.erl
Keep track of the status of the server so we can respond accordingly to requests after `shutdown` and `exit` with the correct exit code, following the protocol specifications.
Fixes #19. Fixes #20.
=> [Fixes #19] [Fixes #20] Shutdown request keep state

src/erlang_ls_methods.erl
LanguageClient does not send the `initializationOptions` field of the config.
According to https://github.com/Microsoft/language-server-protocol/issues/567 heavy reliance on this field is discouraged.
This change allows to successfully connect and start using basic `erlang_ls` functionality in Vim, for example providing `erlc` warnings directly in the editor.
In the future I'd be interested in using Gradualizer with Vim through the language server - this is the first necessary step. [My current Gradualizer integration attempt is sufficient for Vim, but not reusable in other editors.](https://github.com/erszcz/neomake/blob/erlang-gradualizer-wip/autoload/neomake/makers/ft/erlang.vim)
=> Make erlang_ls_protocol_impl:initialize/1 work with autozimu/LanguageClient-neovim

src/erlang_ls_compiler_diagnostics.erl
Avoid generating .beam file with strong_validation option
Fixes #164 .
=> [Fixes #164] Avoid generating .beam file with strong_validation option

src/erlang_ls_completion_provider.erl
Use erlang_ls_utils:find_module/1 and handle all errors, not just not_found.
Fixes #175.
=> [Fixes #175] Use erlang_ls_utils:find_module/1 and handle all errors

src/erlang_ls_compiler_diagnostics.erl
- `debug_info` is not really necessary to generate warnings and errors.
- `basic_validation` is still useful and faster than `strong_validation`, which applies more compiler passess that might take more time.
=> Use minimal compiler options for generating compiler diagnostics

src/erlang_ls_workspace_symbol_provider.erl, test/erlang_ls_workspace_symbol_SUITE.erl
Use a regexp to help a user finding modules in the current workspace. It only works for modules already indexed (i.e. belonging to the same app or already opened). The indexing part will be fixed separately.
=> [#181] Simply use regular expressions to match modules

src/erlang_ls_text_synchronization.erl, test/erlang_ls_definition_SUITE.erl
Don't delete document when it is closed.
Fixes #191.
=> [#191] definition not found after document closed

include/erlang_ls.hrl, src/erlang_ls_completion_provider.erl, src/erlang_ls_poi.erl, test/erlang_ls_completion_SUITE.erl
Implements showing variable names when completing function calls. The variable names are extracted from the function definition and not from the specs, since in general specs don't include variables names. If the argument is not a variable but a pattern, then a default `ArgN` is included where `N` is an integer with the number of the argument.
Fixes #112.
=> [#112] Include function argument names (when available)

README.md, rebar.config, src/erlang_ls.app.src, src/erlang_ls.erl
Don't write logs by default, only when `--log-dir` option is provided.
Fixes #222.
=> [#222] Don't write logs by default

include/erlang_ls.hrl, src/els_code_navigation.erl, src/els_completion_provider.erl, src/els_db.erl, src/els_document.erl, src/els_document_symbol_provider.erl, src/els_hover_provider.erl, src/els_indexer.erl, src/els_parser.erl, src/els_poi.erl, src/els_references_provider.erl, test/els_parser_SUITE.erl
The reason why we added the full tree to the points of interest was because we wanted to get extra information later. But we could just add the information we need at the time of parsing.
Fixes #228.
=> [#228] Remove full syntax tree, add only necessary data

include/erlang_ls.hrl, priv/code_navigation/src/code_navigation.erl, priv/code_navigation/src/code_navigation_extra.erl, priv/code_navigation/src/code_navigation_types.erl, src/els_code_navigation.erl, src/els_completion_provider.erl, src/els_indexer.erl, src/els_parser.erl, src/els_poi.erl, src/els_range.erl, src/els_references_provider.erl, test/els_completion_SUITE.erl, test/els_definition_SUITE.erl, test/els_hover_SUITE.erl, test/els_parser_SUITE.erl, test/els_test_utils.erl, test/els_workspace_symbol_SUITE.erl
* Enable code navigation for remote types
* Rename exports_entry into export_entry for consistency
* Get rid of the "extra" context in the parser
* Pass a location instead of the whole tree to `els_poi:new/X`
* Refactor the parser
Fixes #37 and  #180.
=> [#37] Extract POIs from spec attributes

src/els_io_string.erl, src/els_parser.erl, test/els_completion_SUITE.erl, test/els_io_string_SUITE.erl, test/els_test_utils.erl
Avoid writing to temporary file for parsing.
Fixes #242.
=> [#242] Avoid writing to temporary file for parsing

src/els_config.erl, src/els_indexer.erl
Avoid going over the same subdirs more than once while indexing.
Fixes #229.
The following are the results of calling `ets:i/0` before and after this change (including only relevant tables), to check that the number of items in each table was the same.
```
id              name              type  size   mem      owner
----------------------------------------------------------------------------
documents       documents         set   1967   87944313 els_db
modules         modules           set   1651   25103    els_db
references      references        set   62570  10334672 els_db
signatures      signatures        set   12035  15965340 els_db
```
```
id              name              type  size   mem      owner
---------------------------------------------------------------------------- …
```
=> [#229] Resolve paths recursively only for the ones used with file:path_open/3

priv/code_navigation/src/code_navigation_extra.erl, priv/code_navigation/src/code_navigation_types.erl, src/els_parser.erl, test/els_completion_SUITE.erl, test/els_definition_SUITE.erl
Fixes #241.
I am not distinguishing between types and opaques, but we could change this if the distinction becomes necessary.
=> [#241] Add code navigation for opaque types

src/els_io_string.erl
Use `erlang:binary_to_string/1` instead.
Fixes #252.
=> [#252] Don't assume unicode when getting a binary

src/els_db.erl
Enabling the compression for ETS tables reduces the memory usage quite significantly. The memory used when compressing is roughly 40% of the uncompressed usage.
=> Enable compression for ETS tables

README.md, src/els_config.erl
Configuration option to exclude OTP application from the indexing process.
Fixes #244.
=> [#244] Exclude some OTP applications from indexing

src/els_config.erl
=> [#258] Do not crash when calculating subdirs if a file is named test

README.md
An erlang_ls extension exists for neovim: https://github.com/hyhugh/coc-erlang_ls
This PR adds setup instructions for it in the README.
Fixes #257  .
=> [257] neovim setup instructions

src/els_db.erl, src/els_indexer.erl, src/els_references_provider.erl, test/els_references_SUITE.erl
When indexing a file, remove any references to the previous iteration of the file before adding the current ones.
Fixes #245.
=> [#245] flush references db on update

rebar.config, src/els_code_navigation.erl, src/els_dodger.erl, src/els_parser.erl, test/els_document_symbol_SUITE.erl
Expose functions from `els_dodger` to be able to make a single pass over all the forms. This improves the performance a bit, although not as much as we would have expected.
Fixes #235.
The following are flame graphs captured by running `eflame:apply(els_indexer, index_dir, ["src"]).` and then generating the SVG with the following command:
```
export NAME=stacks; cat $NAME.out | sort | grep -v "<0.349.0>" > "$NAME.out.sort"; _build/debug/lib/eflame/stack_to_flame.sh < $NAME.out.sort > $NAME.svg; open -a Google\ Chrome $NAME.svg
```
=> [#235] Single pass over forms

src/els_parser.erl
`erl_syntax_lib:analyze_attribute/1` generates a `throw` exception, not an `error`.
Fixes #235.
=> [#235] Catch the correct type of exception

src/els_indexer.erl, src/els_methods.erl
Handle generic errors to avoid crashing the els_server process
Fixed #264.
=> [#264] Handle generic errors to avoid crashing the els_server process

src/els_workspace_symbol_provider.erl
From the [`re:compile/2`](http://erlang.org/doc/man/re.html#compile-2) docs:
> Compiling the regular expression before matching is useful if the same expression is to be used in matching against multiple subjects during the lifetime of the program. Compiling once and executing many times is far more efficient than compiling each time one wants to match.
=> [#181] Compile regex before using it multiple times

src/els_compiler_diagnostics.erl, src/els_range.erl, test/els_diagnostics_SUITE.erl, test/els_document_highlight_SUITE.erl, test/els_references_SUITE.erl
Resolve line length for compiler diagnostics, fix calculation for application's range.
Related to #239.
=> [#239] Resolve line length for compiler diagnostics

src/els_methods.erl, src/erlang_ls.app.src
Reports the server version as a `window/showMessage` once initialisation is complete.
Also logs it, if logging is enabled.
Fixes #278.
=> [#278] Report the server version on startup.

priv/code_navigation/src/code_navigation.erl, src/els_parser.erl
Re-add the `try...catch` for `syntax_error`s. 
Fixes #283.
=> [#283] Don't fail with function name as macro

priv/code_navigation/elvis.config, priv/code_navigation/src/elvis_diagnostics.erl, rebar.config, rebar.lock, src/els_elvis_diagnostics.erl, src/els_text_synchronization.erl, src/els_utils.erl, src/erlang_ls.app.src, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl, test/prop_statem.erl
Generates Elvis diagnostics when a file is saved, so long as an Elvis configuration exists.
Add [elvis](https://hex.pm/packages/elvis_core) as a diagnostics source.
Fixes #260 .
=> [#260] Elvis diagnostics

src/els_utils.erl
Handle `nomatch` result for `string:prefix/2`. Depending on what the client provides as a `root_uri`, the value might or might not include a trailing `/`, we should handle both cases.
Fixes #289.
=> [#289] Handle nomatch for string:prefix/2

src/els_client.erl, src/els_jsonrpc.erl, src/els_server.erl, src/els_stdio.erl, src/els_stdio_client.erl, src/els_tcp.erl, src/els_tcp_client.erl, src/els_transport.erl, test/els_test_utils.erl, test/prop_statem.erl
Part of a long-due cleanup on how the two transports (tcp, stdio) are used by client and server.
Fixes #296 .
=> [#296] Split client in tcp_client and stdio_client

src/els_dt_document.erl, src/els_indexer.erl, test/els_indexer_SUITE.erl, test/els_indexer_SUITE_data/test.erl
Dropping the `.src` extension as well, since we are not handling it anyway.
Fixes #313 .
=> [#313] Do not crash on un-supported extensions

src/els_dt_document.erl, src/els_indexer.erl, test/els_indexer_SUITE.erl
Files like `rebar.config` or `application.app.src` should have the server's features available, so we should index files with unknown extension and assign kind `other` to them.
Fixes #313.
=> [#313] Index files with unknown extension and assign 'other' kind

.github/workflows/build.yml
Unfortunately, there's no Erlang installed by default on Windows or Mac systems and the existing `setup-erlang` actions do not work on Windows or Mac, so we would need to write one. For the time being, I'm simply adding a Linux-based workflow that we can keep in parallel to the Travis CI pipelines, to verify how both behave, which one is faster and so on. So, see this PR as a contribution to #152 which prepares #305.
=> [#305] Build Workflow using GitHub Actions

src/els_workspace_symbol_provider.erl
Limit the amount of workspace symbols returned.
Fixes #323.
=> [#323] Limit the amount of workspace symbols returned

README.md, src/els_config.erl, src/els_dialyzer_diagnostics.erl
Add a new `plt_path` configuration option. When it's not defined dialyzer diagnostics are not available.
I'm leaving the code lens approach we discussed for the future.
Fixes #329.
=> [#329] Missing dialyzer diagnostics

src/els_compiler_diagnostics.erl
=> [#340] Only compile .erl files until we implement wrappers for .hrl files

README.md, src/erlang_ls.app.src, src/erlang_ls.erl
Use platform dependent log directory.
Fixes #335.
=> [#335] Use platform dependent log directory

rebar.config, src/els_dialyzer_diagnostics.erl, src/erlang_ls.app.src
Remove dialyzer (which depends on wx) from required applications.
Fixes #330.
=> [#330] Remove dialyzer (which depends on wx) from required applications

src/els_client.erl, src/els_methods.erl, test/prop_statem.erl
Not doing anything on cancellation, since the protocol does not enforce any specific behaviour (e.g. single threaded servers will not be able to cancel requests). We could implement real cancelling, but it seems like overkill at this stage. For now, let's just handle the requests in a dummy way to avoid the annoying "method not implemented" messages displayed to the clients.
Fixes #18 .
=> [#18] Add stub for cancellation support

elvis.config, priv/code_navigation/src/my_gen_server.erl, src/els_client.erl, src/els_implementation_provider.erl, src/els_methods.erl, src/els_provider.erl, test/els_implementation_SUITE.erl, test/els_test_utils.erl, test/prop_statem.erl
A maybe opinionated way to use the _implementation_ provider to navigate to callback functions for OTP behaviours.
Something that I longed for a long time was the ability to navigate from a call such as `gen_server:call(...)` to the respective `handle_call`. To limit the magic happening, this is restricted to the same module.
Fixes #363.
=> [#363] Add implementation provider and support for gen_server callbacks

src/erlang_ls.erl
This level was lowered to INFO in the old times when the whole buffer
content was part of the DEBUG logs, making them un-readable. This is
not the case any longer, so the change can be reverted. DEBUG messages
include the actual request/response messages, which is vital to find
the root cause of a bug.
Fixes #377 .
=> [#377] Show debug level logs in debug mode

src/els_methods.erl, src/els_stdio.erl, src/els_utils.erl, test/prop_statem.erl
Handle method 'exit' received from the stdio transport.
Also change halt to init:stop to tear down gracefully.
I see in the meantime `els_db:stop(),` call was added, I think this can be removed as `init:stop` should tear down the applications in dependency order. 
Fixes erlang-ls/vscode#11 .
=> fix not shutting down properly when using stdio transport

README.md
Since we are not really using the `erlang/config_path` I would leave it un-documented for now.
After all, it's not clear for the final user how to set it, since it requires control on the client.
Fixes #382 .
=> [#382] Refactor config instructions

src/els_methods.erl
Some clients such a vscode send this message on startup, it results in
a confusing pop-up message on the client.
Fixes #373
=> Add nop `workspace/didChangeconfiguration` processor.

src/els_dodger.erl, src/els_dt_document.erl, src/els_dt_references.erl, src/els_indexer.erl, src/els_parser.erl, src/els_poi.erl
There were various errors.
We should perhaps run edoc as part of the `make` process.
=> Clean up edoc comments

README.md, src/els_config.erl, src/els_text_synchronization.erl, test/els_diagnostics_SUITE.erl
One of the features that I miss most when coming from EDTS is the ability of hot code reloading my changes.
This PR introduces this ability and should help in getting users of EDTS switched over to erlang_ls.
There are a few things in this PR that I'm not a huge fan of and I'm happy to discuss:
- I have not found a nice way of being able to test this functionality in a test SUITE.
I have exported the function that is called using `ifdef(TEST)` (which I personally generally dislike),
after trying several ways this seemed like the least intrusive way of testing this.
If you'd prefer another approach, please let me know.
- Ideally I'd like to provide the Mod and Function that should be used to recompile as part of a config as well.
This to aid any users that have implemented some custom way …
=> Implement functionality for hot code swapping

rebar.config, src/erlang_ls.app.src
Remove unused `debug_mode` application variable.
=> [#430] Remove unused debug_mode application variable

priv/code_navigation/src/diagnostics_behaviour.erl, priv/code_navigation/src/diagnostics_behaviour_impl.erl, src/els_compiler_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
Fixes #406 .
Notice that the Dialyzer message about "callback info missing" needs to be addressed separately.
=> [#406] Add support for custom behaviours

src/els_tcp.erl
This matches the stdio behaviour, as per #379
Fixes https://github.com/erlang-ls/vscode/issues/11
=> Inject exit message when TCP socket is closed.

rebar.config
A tag is not yet available for the latest version of redbug, so let's keep an eye on that.
Fixes #438 .
=> [#438] Use upstream redbug again

src/els_dialyzer_diagnostics.erl
Today I tried to add `plt_path` to one of my projects but realized that dialyzer was not reporting any errors. The reason turned out to be that `dialyzer:run/1` was unable to operate on the src code since it was unable to find the includes that were required. 
Adding the `include_dirs` option solved the problem. 
Note:
I did not add a test for this since I was unable to find any dialyzer tests at all? Unless I'm mistaken, I suggest we add an issue for adding some tests for `els_dialyzer_diagnostics`
=> Add include_dirs as additional option to dialyzer:run/1 in els_dialyzer_diagnostics

src/els_methods.erl
We can end up running multiple LSP servers for a given project. This makes it
clear where each one is running.
=> Add root uri basename to startup message.

priv/rebar3_release/erlang_ls.config, src/els_config.erl, test/els_initialization_SUITE.erl
Provide the ability to set config file location via the Initialize request.
In javascript terms, this is expected to be
erlang.config_path
The value can be absolute or relative, and can include the name of the file to
be loaded as well, otherwise is treated as a path.
Fixes #440 .
=> [#440] global config

README.md
Slight expanding of README. Mentions that yarn version distributed by brew for OSX is broken, and gives explicit link to coc-erlang_ls config help.
Fixes 257.
=> [257] add extra link for coc-erlang_ls config, mention broken yarn

src/els_compiler_diagnostics.erl, src/els_diagnostics_utils.erl, src/els_dialyzer_diagnostics.erl
=> [#471]: Ensure behaviour info can be found by Dialyzer by adding dependencies to files opt

src/els_text_synchronization.erl, test/els_diagnostics_SUITE.erl
After raising #468 I found that with a minor rewrite we could work around the slowness of Dialyzer by performing Elvis and Dialyzer checks asynchronously. The (opinionated) view here being that compiler diagnostics and the ability to use code_reload and run your tests quickly are more important than seeing Dialyzer and Elvis warnings in your editor. 
They still show up but with a slight delay. Basically the flow went from:
- compile -> dialyzer -> elvis -> code_reload -> notify editor
to:
- compile -> code_reload -> notify editor -> dialyzer -> elvis -> notify editor 
For the end-user very little changed other than that Dialyzer and Elvis warnings come with a slight delay after the user has been notified of compiler warnings / code_reload result. 
Fixes #468
=> 468 async dialyzer and elvis checks

src/els_indexer.erl, src/els_methods.erl, src/els_text_synchronization.erl, test/els_references_SUITE.erl
Check MD5 before parsing file content.
Fixes #481.
=> [#481] Check MD5 before parsing file content

.github/workflows/build.yml
Enable running GitHub actions for pull requests to `master` (when they are created, updated or re-opened) and pushes to `master` (when the PRs are merged).
See [here](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request) for documentation on what events are available.
Fixes #500.
=> [#500] Run GitHub actions when pull request is opened

README.md
I'm honestly not exactly sure how the `code_reload` should be structured from a `yaml`-purist perspective but plenty of yaml-examples I find use the following standard. 
Currently it's confusing since it's not well documented and most users would assume which is "wrong" according to how the code is written :cry: 
```yaml
code_reload:
- node: foo@example
```
Since the test uses meck, the test didn't catch this which I'll see how to resolve in a PR that I'm working now that follows up on: https://github.com/erlang-ls/erlang_ls/pull/469 (cleaning up the code now and finalizing some Dialyzer tests)
=> Fix readme for code reload

src/els_dialyzer_diagnostics.erl
The diagnostics returned for dialyzer contained a negative column number which prevented any other diagnostics to be reported in VS Code.
Fixes #413 .
=> [#413] Avoid negative columns

src/erlang_ls.erl
Enable logging when log level is provided and is not 'none'.
Fixes #507.
=> [#507] Enable logging when log level is provided and is not 'none'

priv/code_navigation/src/code_navigation.erl, src/els_hover_provider.erl, test/els_document_highlight_SUITE.erl, test/els_hover_SUITE.erl, test/els_references_SUITE.erl
Hovering over export entries shows information.
Fixes #484.
=> [#484] Hovering over export entries shows information

src/els_code_action_provider.erl, src/els_execute_command_provider.erl, test/els_code_action_SUITE.erl, test/prop_statem.erl
The LSP executeCommand process requires the commands to be first registered with
the client. Vscode has a single registry of commands, for the entire client, and
shuts down a server if it tries to register a duplicate command.
This diff ensures that all commands used are unique, by prepending the
underlying operating system process id to the command when registered and used.
Fixes #514.
=> [#514] Register commands with a unique prefix

src/els_config.erl
Otherwise dependencies are not found, and thus parse_transforms are
not included when compiling.
=> Search configured include_paths

src/els_sup.erl
Replace group leader when using stdio transport.
Fixes #518.
=> [#518] Replace group leader when using stdio transport

src/els_hover_provider.erl, test/els_hover_SUITE.erl
Use syntax highlighting when using markdown to show information on hover.
Fixes #516.
=> [#516] Use syntax highlighting when using markdown to show information on hover 

rebar.config, rebar.lock, src/els_config.erl, src/els_db.erl, src/els_dt_document.erl, src/els_dt_document_index.erl, src/els_dt_references.erl, src/els_dt_signatures.erl, src/els_indexer.erl, src/els_methods.erl, src/els_text_synchronization.erl, src/els_utils.erl, src/erlang_ls.app.src, test/els_indexer_SUITE.erl, test/els_indexing_SUITE.erl, test/els_rebar3_release_SUITE.erl, test/els_references_SUITE.erl, test/els_test_utils.erl, test/prop_statem.erl
This Pull Request completely revisits the indexing process. In the sample code base I'm experimenting with (~1.5 million lines of code) the "waiting" time on a restart (i.e. with an existing DB which needs to be loaded in memory) went from ~1 minute to ~17 seconds. I would appreciate if you could try it with other code bases too. This PR also gets rid of the worker pool for indexing, preparing for a follow-up PR where we can display indexing progress to the user.
Main changes:
* Remove worker pool for indexing
* Force a DB dump after indexing (so it's done in the background instead of on restart)
* Do not compress tables (with a little loss in terms of memory, we gain a lot in loading speed)
* Introduce `shallow` cloning for OTP libraries (i.e. do not store references for OTP libraries, …
=> [#463] Speed up indexing

include/erlang_ls.hrl, src/els_db.erl, src/els_folding_range_provider.erl, src/els_parser.erl, test/els_foldingrange_SUITE.erl
Fix off by one in folding ranges.
Fixes #534.
=> [#534] Fix off by one in folding ranges

.github/workflows/build.yml
Title should speak for itself but https://github.com/erlang-ls/erlang_ls/commit/3701764fbbd81c0374dd3f72999c1f266bf9426e had the side effect of no longer running Github Actions for branches but only on pull request or for `master`
Fixes #539
=> [#539] Run github actions on push of any branch

.github/workflows/build.yml
Based on thee discussion [here](https://github.com/actions/checkout/issues/23#issuecomment-572688577) it seems `actions/checkout@v2` has solved this issue.
Fixes #542.
=> [#542] Bump checkout action to v2

include/erlang_ls.hrl, priv/code_navigation/include/code_navigation.hrl, priv/code_navigation/src/code_navigation.erl, src/els_completion_provider.erl, src/els_dt_signatures.erl, src/els_parser.erl, src/els_range.erl, test/els_completion_SUITE.erl
Auto complete types when in a `spec` or `export_types` context.
Fixes #458.
=> [#458] Auto complete types

README.md, elvis.config, src/erlang_ls.app.src, src/erlang_ls.erl, test/erlang_ls_SUITE.erl
Using getopt allows us to get some nice features for free like an easy utility function for getting out the version from Erlang LS and getting a `help` to keep the arguments to Erlang LS and the documentation of them in one place.
Fixes #476 
Thanks [@sgillis](https://github.com/sgillis) and [@libanomarsweden](https://github.com/libanomarsweden) for helping out! :+1: 
Edit: Can someone restart the Github action for me? It passed on my Github account when I had https://github.com/erlang-ls/erlang_ls/pull/540 on top of this branch so it seems like a Github problem to me
=> 476 use getopt for cli arg parsing

include/erlang_ls.hrl, priv/code_navigation/src/code_navigation_extra.erl, src/els_completion_provider.erl, src/els_parser.erl, src/els_range.erl, test/els_completion_SUITE.erl, test/els_references_SUITE.erl
This PR introduces an adaptation of the `erl_syntax_lib:fold/3` function, so that only some of the subtrees are processed for specific types of syntax tree nodes.
Fixes #110.
=> [#110] Add auto-completion for atoms

Makefile, rebar.config
By default erlang nodes will try to make a fully connected net of all
erlang nodes discovered. We don't want that 'erlang_ls' nodes interfer
with other testing nodes on the same machine.
Also avoids confusing mnesia when several different schemas might
exist in the same group of nodes. Mnesia wants the same schema on all
nodes in the group.
An alternative solution is to make the nodes hidden, but that
might make connecting and inspecting the nodes harder.
If we later want to create a mesh of nodes this needs to be
revised, maybe use global_groups?
Fixes # .
=> Do not make large node groups

src/els_utils.erl
If the top level directory (`RootPath`) is symlinked, then checking the parent of
the immediately descendent of the root should not fail for the symlink.
Fixes #520.
=> Fix corner case in els_utils:is_symlink

src/els_completion_provider.erl, src/els_parser.erl, src/els_provider.erl, test/els_completion_SUITE.erl, test/els_fake_stdio.erl
Implements auto-completion for Erlang built-in functions and types. 
There's one caveat which is that the built-in functions are resolved dynamically based on the Erlang/OTP release in which **Erlang LS is running** and not the Erlang/OTP release specified in the **erlang_ls.config**. 
I considered trying to figure out what the were BIFs by parsing the clauses from source code in `erl_internal:bif/2`, but decided against it. It seemed overkill given that even though BIFs get added, they don't change that much.
A possible improvement would be to resolve them only once when the provider is initialized instead of resolving on every completion.
The list of built-in type is a hardcoded list taken from the information [here](https://erlang.org/doc/reference_manual/typespec.html).
Fixes #106.
=> [#106] Auto-complete built-in functions and types

rebar.config, src/erlang_ls.erl
* Remove `debug` mode, keeping the alias
* Enable logging by default
Fixes #560 .
=> [#560] Remove separation between debug and default mode

src/els_db.erl, src/els_utils.erl
This ensures that spaces in the path are treated correctly.
Exchange `os:cmd` for a call to `open_port({spawn_executable ...`, adjusted from https://stackoverflow.com/a/2249387/542190.
Fixes https://github.com/erlang-ls/vscode/issues/24.
=> Use open_port to spawn epmd

.github/CONTRIBUTING.md
Add a missing "be"
Fixes a very small typo in the documentation
=> Fix a very small typo

include/erlang_ls.hrl, src/els_db.erl, src/els_document_highlight_provider.erl, src/els_dt_references.erl, src/els_indexer.erl, src/els_range.erl, src/els_references_provider.erl, test/els_definition_SUITE.erl, test/els_references_SUITE.erl
Implements finding references for types. Tightens the `id` field type definition for `poi()`s.
Fixes #486. Fixes #368.
=> [#486] Find references for types

rebar.config
The current version of lager is from 22 December 2018. No big reason for the bump, except avoiding falling too much behind.
Fixes #581 .
=> [#581] Bump lager from 3.6.8 to 3.8.0

src/els_methods.erl
Use the current working directory as `rootUri` when missing.
After trying different things and giving it some thought I decided to go for the simplest approach. Please check the comments in the related issue #400 and share your thoughts.
=> [#400] Use the current working directory as rootUri when missing

Makefile, src/els_code_action_provider.erl, src/els_compiler_diagnostics.erl, src/els_completion_provider.erl, src/els_config.erl, src/els_dialyzer_diagnostics.erl, src/els_document_symbol_provider.erl, src/els_elvis_diagnostics.erl, src/els_execute_command_provider.erl, src/els_hover_provider.erl, src/els_indexing.erl, src/els_io_string.erl, src/els_methods.erl, src/els_stdio_client.erl, src/els_text.erl, src/els_text_edit.erl, src/els_text_synchronization.erl, src/els_utils.erl, test/els_fake_stdio.erl, test/els_indexer_SUITE.erl, test/els_indexing_SUITE.erl, test/els_proper_gen.erl, test/els_rebar3_release_SUITE.erl, test/els_test_utils.erl
The previous PR assumed all string were always unicode, this is not the case. This PR also remove the `debug` target from the `Makefile` and adds an `install` target which can be evolved as needed (e.g. to support Windows).
Fixes #306.
=> [#306] Handle non-unicode as well

src/els_uri.erl, test/els_references_SUITE.erl
Windows `file://` URIs are quite a bit different than Unix `file://` in that they can contain a host (for UNC paths like `\\some_server\some_share` and that the `/` prefix has to be stripped in `file:///c:/some_path`. Also, the colon usually gets URI-encoded which needs to be undone.
=> Implement file URI handling for Windows

src/els_parser.erl, src/els_range.erl, test/els_document_highlight_SUITE.erl
Add 'imported' flag to auto-imported built-in functions.
Fixes #527.
=> [#527] Add 'imported' flag to auto-imported built-in functions

src/els_db.erl, src/els_dt_signatures.erl, src/els_hover_provider.erl, src/els_indexing.erl, src/els_parser.erl
In this PR we pre-calculate the pretty-printed version of the specs during indexing. This avoids to store (sometimes huge) syntax trees in the DB and un-necessary recalculation of those specs. I realized we store the specs twice, both in the _document_ table and the _signatures_ table. For the time being I'm leaving things as they are (after all the _signatures_ table is just an index), but we should consider storing them once.
I tried this change both in the `erlang_ls` codebase and in a bigger codebase (1.5 millions lines of code). Here are some number.
|               | Before | After  |
|---------------|--------|--------|
| Document DB   | 195 MB | 165 MB |
| Signatures DB | 31 MB  | 1MB    |
|               | Before | After  |
|---------------|--------|--------|
| Document DB   | 577 …
=> [#606] Precalculate specs

.github/workflows/build.yml
For now let's at least build and publish the docs as an artifact. We can publish the `master` docs as a static website later on, if we want.
Fixes #589 .
=> [#589] Produce and publish edoc

include/erlang_ls.hrl, priv/code_navigation/test/sample_SUITE.erl, rebar.config, src/els_client.erl, src/els_code_action_provider.erl, src/els_code_lens.erl, src/els_code_lens_ct_run_test.erl, src/els_code_lens_server_info.erl, src/els_command.erl, src/els_command_ct_run_test.erl, src/els_compiler_diagnostics.erl, src/els_cth.erl, src/els_diagnostics.erl, src/els_dialyzer_diagnostics.erl, src/els_elvis_diagnostics.erl, src/els_execute_command_provider.erl, src/els_range.erl, src/els_text_synchronization.erl, test/els_code_lens_SUITE.erl, test/els_execute_command_SUITE.erl, test/els_test_utils.erl, test/prop_statem.erl
This PR introduces a new _Code Lens_ and a _Command_, named "ct-run-test", through which is now possible to run Common Test testcases by clicking on a button from a test suite.
The code lens is activated automatically whenever the `ct.hrl` header is included in a module. The lens will be enabled for all functions of arity `1` in the test suite and a _blacklist_ avoids functions such as `init_per_suite/1` or `end_per_suite/` to be included.
The CT test is executed as a _background job_ and a CT hook is used to report diagnostics in case of failed or skipped tests.
I used this opportunity to refine the _code lens_ behaviour, introducing some extra callbacks that should hopefully simplify the creation of new code lenses. I will document the behaviour properly once the API is settled.
More …
=> [#604] Add run-ct-test code lens, refactor code lens behaviour

priv/code_navigation/src/diagnostics_xref.erl, src/els_diagnostics.erl, src/els_xref_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
_Xref_ diagnostics will report an error for all those cases where a function _application_, an _implicit fun_, an _import_ or _export_ entry does not have a corresponding definition in the server, resembling what `xref` would do. The advantage, compared to `xref`, is that these diagnostics operate on the POI/DB level and don't require _binaries_ or `debug_info`.
Based on top of  #616 , which should be merged first (and this one rebased on top of the latest master).
Fixes #156.
=> [#156] Xref diagnostics

src/els_general_provider.erl, src/els_methods.erl
The major advantage of this PR (apart from having a more consistent codebase in the `els_methods` module) is to serialize _general_ requests via the dedicated provider. After moving only the `initialize` request, I noticed some flakyness in the proper tests which was due to these messages being handled in the wrong order.
Fixes #622 .
=> [#622] Use general provider consistently

src/els_client.erl, src/els_protocol.erl, src/els_server.erl, src/els_stdio_client.erl, src/els_tcp_client.erl
Fixes #613.
Them not being the same causes confusion - both `els_client` and `els_server` use the protocol, but their message sending callbacks have slightly different type signatures. This difference is typically unimportant, but in the case of OTP21.0 `io:format` (used by `els_stdio`) it crashes, and "rightfully", as its spec does not include `iolist()`.
It's been pointed out that in practice the code does work in most other OTP versions but the disparity is still incorrect in its own right.
=> Unify ElsClient:send/2, ElsTransport:send/2 types

src/els_general_provider.erl, src/els_provider.erl
This addresses some issues trying to use erlang_ls with vim/coc. Specifically vim was sending the initialization options as an empty string and the general provider init was timing out.
Fixes # .
=> Handle initializationOptions being empty string and fix timeout

include/erlang_ls.hrl, src/els_code_lens.erl, src/els_code_lens_show_behaviour_usages.erl, src/els_db.erl, src/els_dt_references.erl, src/els_execute_command_provider.erl, src/els_indexing.erl, src/els_parser.erl, src/els_range.erl, src/els_references_provider.erl, test/els_code_lens_SUITE.erl
Whenever opening a _behaviour_ module (defined as an Erlang module defining one or more callback functions), shows the number of usages of such a behaviour (defined by the presence of a `-behaviour` attribute) in the code base.
Fixes #626.
=> [#626] Add code lens which shows behaviour usages

README.md, src/erlang_ls.erl
=> [#630] Remove old_port as option in escript

src/els_parser.erl
Fixes #633 
**TIL**, when taking all functions that are listed as bifs in `erl_internal:bif/2` and checking if they're part of the `erlang`-module, I found that `is_bitstr/1` and `monitor/3` are not. I cannot find a trace of `is_bitstr/1` other than it was introduced in R11 by the looks of it nor `monitor/3`. My guess is that they were removed a long time ago but simple not removed from the `erlang_internal:bif/2` list.
=> [#633] Follow up on #598: Do not consider all exports from erlang module as bifs

priv/code_navigation/erlang_ls_diagnostic.config, src/els_config.erl, src/els_diagnostics.erl, test/els_initialization_SUITE.erl
Via erlang_ls.config
Also validate that the enabled providers actually exist.
Fixes #650.
=> [#650] Allow configuration of diagnostics providers

src/els_code_lens.erl, src/els_config.erl, test/els_initialization_SUITE.erl, test/els_initialization_SUITE_data/diagnostics_invalid.config, test/els_initialization_SUITE_data/lenses_custom.config, test/els_initialization_SUITE_data/lenses_invalid.config
Fixes #657 .
Please notice how the configuration option has been renamed to `lenses` for simplicity.
=> [#657] Be able to configure lenses via config file

src/els_code_lens_ct_run_test.erl, test/els_code_lens_SUITE.erl, test/els_initialization_SUITE.erl, test/els_initialization_SUITE_data/lenses_invalid.config
The lens is not quite stable yet, so let's not set false expectations.
Fixes #666 .
=> [#666] 😈 Disable ct-run-test lens by default

README.md
The new configuration page also includes information about diagnostics and lenses.
Fixes #650.
=> [#650] Move config options to website

src/els_uri.erl
I must have messed up something in the Regex, it didn't match for some reason in `re:run`, it does in `re:replace`...
=> Fix leading slash stripping for Windows

src/erlang_ls.erl
This is the most common case, and in general if specifying tcp transport a port
needs to be specified too, as clients will launch multiple instances under some
circumstances.
=> Change default transport to stdio

src/els_general_provider.erl, test/els_execute_command_SUITE.erl, test/els_test_utils.erl
Now that all calls go through a provider, this should enable us to move the `wait-for-tables` from the `initialize` to the `initialized`. This should mean a much faster prompt for the user in big code bases and a happy @alanz .
Requests performed by the client before the DB is ready should simply queue / time out.
The fact that we now show progress reports with percentages should also help users in understanding when the server is fully ready.
Please try this on big code bases and try to break it.
Fixes #319 .
=> [#319] Wait for tables after initialize

priv/code_navigation/src/diagnostics_parse_transform_usage_list.erl, src/els_parser.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
Compile options in the module is a list, and several parse transforms can be specified there.
=> Detect parse transforms properly.

rebar.config
Otherwise it does not download for unauthenticated users.
=> Use https transport for rebar3_erlang_ls plugin config

misc/dotemacs
The `which-key` package is supported by Emacs' `lsp-mode` and it offers a nice interface towards LSP shortcuts. The prefix has been changed to be a bit friendlier to Mac users.
Here is what it looks like:
Fixes #718
=> [#718] Customize prefix for key-bindings, add which-key integration

misc/dotemacs
=> [#720] Always show diagnostics at the bottom, using 1/3 of the available space

.github/workflows/build.yml
There's currently not an easy way to blacklist a specific dir or file via wildcards (e.g. the `log_private` dir which contained the DB), so the artifacts are huge. Once the feature is available in the `upload-artifact` GitHub action we can add that filtering. See:
https://github.com/actions/upload-artifact/issues/44
Fixes #609 .
=> [#609] Store CT Logs as artifacts

src/els_config.erl, src/els_utils.erl
All erlang files in a subdir of RootUri should be found,
not only files below 'src', 'test' or 'include'.
=> Add all subdirs to search path

src/els_indexing.erl, src/els_uri.erl
The indexed data was wrong on Windows (crashes also the tests) due to a mismatch between `file:///c:/some/path` and `file:///c%3a/some/path` URIs. With this, the common test suite finally runs through.
=> Fix indexing on Windows

src/els_utils.erl
If a module have several Uris prioritize them.
Search for project related Uri first and prioritize modules in src dir.
When working OTP reposiory we get at least two uris per module, one
in src tree and one in otp release tree, when jumping to definition
we want to jump to the one in the src tree and not to the release tree.
Also some modules names are duplicated in tests dir, avoid these too.
Now that the indexing is parallel the order is random, so it's not
given where to go.
=> Prioritize Uris

src/els_stdio.erl
The notification sending was failing with badarg
if the notification text had ~p or similar.
=> Handle message as string, not as pattern.

.gitpod.yml
=> [#713] Bump Erlang LS VSCode extension to 0.0.11 in .gitpod.yml

src/els_uri.erl
=> [#725] Do not crash if the Uri contains spaces

src/els_compiler_diagnostics.erl, test/els_diagnostics_SUITE.erl
The diagnostic processing calles 'Module:format_error/1' to render diagnostics.
For included files we render these ourselves, and wrap them in a context
message. Do not pass the wrapped messages on to the original fomatter again.
=> Fix crash from asking erl_lint format our own error messages

src/els_compiler_diagnostics.erl
The load fails, and generates spurious diagnostics for the user.
=> Do not attempt to load dependencies from sticky directories

src/els_completion_provider.erl
Current code of `els_completion_provider` has branches for
- `COMPLETION_TRIGGER_KIND_CHARACTER`
- `COMPLETION_TRIGGER_KIND_INVOKED`
but the `COMPLETION_TRIGGER_KIND_FOR_INCOMPLETE_COMPLETIONS` branch is missing.
In my environment, the following crash occured:
```
2020-05-30 13:11:32.825 [error] <0.201.0>@els_methods:dispatch:69 Unexpected error [type=exit] [error={{{case_clause,3},[{els_completion_provider,handle_request,2,[{file,"/home/shino/g/erlang_ls/src/els_completion_provider.erl"},{line,46}]},{els_provider,handle_call,3,[{file,"/home/shino/g/erlang_ls/src/els_provider.erl"},{line,80}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{g …
```
=> Add COMPLETION_TRIGGER_KIND_FOR_INCOMPLETE_COMPLETIONS branch

src/els_execute_command_provider.erl
This lists the value of the 'otp_path' configuration variable, and also the
'code:root_dir()' value if it differs.
This can be accessed by enabling the "server-info" code lens in erlang_ls.config
lenses:
enabled:
- server-info
and invoking it.
May help in debugging #767 .
=> [#767] Update "server-info" lens to give OTP Path too.

src/els_general_provider.erl
As suggested in #637
Note: it does not show up in the UI in vscode 1.46.1, in any obvious way.
=> [#637] Provide serverInfo in initialize response message

.gitmessage
This helps nudge contibutors to follow the contribution guidelines, as per
https://github.com/erlang-ls/erlang_ls/blob/master/.github/CONTRIBUTING.md#commit-messages
Fixes #765 .
=> [#765] Add commit message template.

src/els_code_navigation.erl, src/els_diagnostics_utils.erl
If there is a dependency loop in include files, then els_diagnostics_utils:dependencies/1 would infinitely recurse.  
I've added a simple set of previously-visited uris to prevent such loops from occuring
=> Added loop detection into dependency discovery

src/els_general_provider.erl
Signed-off-by: Saurav Tiwary <srv.twry@gmail.com>
This PR disable the `includeText` flag while saving a text document since the files are processed from the disk hence the text isn't required.
Fixes #771
=> [#771] Do not ask for text on file save

.github/workflows/build.yml, test/els_execute_command_SUITE.erl, test/els_test_utils.erl
* Bump OTP image to 23.1
* Ensure DB is up and running when performing manual indexing
* Refactor helper function
Fixes #796 .
=> [#796] Fix CI pipeline for OTP 23

src/els_uri.erl
Reference: erlang/otp@40efd73
Fixes #800 .
=> [#800] Ensure the path is recognized by OTP 23.1 as an absolute one

src/els_sup.erl
Otherwise the shell_docs:render does not receive an encoding, and causes a crash
when requesting information for hover requests.
Fixes #754
=> [#754] Return the original io:getopts/0 values in noop_group_leader.

src/els_db.erl
Prior to release 0.5.1, the database could end up with faulty URI entries in it
if run using OTP 23.
The solution is to delete the database so that it is rebuilt.
This commit bumps the database version number, so this happens automatically.
=> Bump DB Schema version for force DB rebuild

src/els_dap_general_provider.erl, src/els_db.erl, src/els_db_server.erl, src/els_db_table.erl, src/els_distribution_server.erl, src/els_dt_document.erl, src/els_dt_document_index.erl, src/els_dt_references.erl, src/els_dt_signatures.erl, src/els_general_provider.erl, src/els_indexing.erl, src/els_sup.erl, src/els_utils.erl, test/els_indexing_SUITE.erl, test/els_test_utils.erl
For now, let's switch back to plain ETS. We can then follow up by adding persistence (via DETS) if necessary. In that case, we could have a dedicated option in the `erlang_ls.config` file to enable it. Before adding persistency, we should really check if it's worth, performance-wise.
All write operations to the ETS tables are serialized via a `gen_server`. Reads happen straight from the ETS table, which has `read_concurrency` enabled, even if it shouldn't matter much in Erlang LS.
Fixes #770 .
=> [#770] Switch back from Mnesia to simple ETS

priv/code_navigation/src/diagnostics_xref_pseudo.erl, src/els_xref_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
The functions
record_info/2
module_info/0
module_info/1
are pseudo functions generated and processed by the erlang compiler. Do not
report xref errors if they are encountered, as they are always valid.
Closes #641.
Closes #644.
=> [#641] do not report xref errors for pseudo functions

include/erlang_ls.hrl, priv/code_navigation/include/definition.hrl, priv/code_navigation/include/transitive.hrl, priv/code_navigation/src/diagnostics_unused_includes.erl, src/els_compiler_diagnostics.erl, src/els_diagnostics.erl, src/els_diagnostics_utils.erl, src/els_unused_includes_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
This approach is not particularly performant and it detects a few false positives, but - considering this is disabled by default and currently undocumented -, I believe it's a step in the right direction. We can refine the algorithm incrementally.
Fixes #404 .
=> [#404] Add experimental diagnostics to detect unused included files

src/els_crossref_diagnostics.erl, src/els_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_initialization_SUITE.erl, test/els_initialization_SUITE_data/diagnostics_custom.config, test/els_initialization_SUITE_data/diagnostics_invalid.config
This is an internal erlang_ls diagnostic, based on the results of indexing.
The name 'xref' causes people to think it is a version of the 'xref' tool.
This also opens the way to provide an integration of the actual 'xref' tool at a
fututure date.
=> Rename xref diagnostics to crossref

src/els_dap_general_provider.erl, src/els_distribution_server.erl, src/els_general_provider.erl
=> [#812] Use project basename for ELS and DAP node names

include/erlang_ls.hrl, priv/code_navigation/src/rename.erl, priv/code_navigation/src/rename_usage1.erl, priv/code_navigation/src/rename_usage2.erl, src/els_client.erl, src/els_general_provider.erl, src/els_methods.erl, src/els_parser.erl, src/els_provider.erl, src/els_range.erl, src/els_rename_provider.erl, test/els_rename_SUITE.erl, test/els_test_utils.erl
* Introduce plumbing for textDocument/rename
* Implement renaming for callback functions
* Index function_clauses
* Fix range for callbacks
Still not included:
* Renaming of function callers
From Emacs:
```
lsp-rename
```
Fixes #820 .
=> [#820] Add support for renaming callback functions

src/els_code_navigation.erl
Under some circumstances, e.g. a slightly misconfigured project or one using the
proper rebar3 plugin, a `Uri` reference may result in `{error, enoent}` in
`els_code_navigation:find_in_document/5`.
Detect any unmatched errors in it, and convert them to `{error, not_found}`
result.
=> More robust els_code_navigation:find_in_document/5

src/els_compiler_diagnostics.erl, src/els_escript.erl
I've been reviewing https://github.com/erlang/otp/pull/2664 and found that erlang ls breaks some abstractions when it comes to handling `erl_anno` annotations. This PR fixes those.
I also start using the "fixed" epp:open/1 instead of the undocumented epp:open/5 for parsing escripts. https://github.com/erlang/otp/pull/2664 has not been merged yet, so the API may still change, but I thought we may as well fix it now.
=> Fix column numbers

README.md
=> [#835] Move CI badge from Travis CI to GitHub Actions

elvis.config, priv/code_navigation/src/code_navigation.erl, src/els_range.erl, src/els_rename_provider.erl, test/els_diagnostics_SUITE.erl, test/els_document_highlight_SUITE.erl, test/els_references_SUITE.erl, test/els_rename_SUITE.erl
Add test for various highlight ranges. Also fixed various bugs found when implementing the tests.
As you said in the other PR, we really need a better way to test this. Also, the way that the ranges is done is very fragile as you can just insert a space somewhere and it will break. i.e.
```erlang
fun 
lists
:
foldl
/
3.
```
The poi range for this incorrect, but the above is correct (though unusual) code. Not to mention if we start putting strange unicode characters in the code... Maybe I'll see what I can do about that after the holidays.
This PR at least is an improvement :)
=> Add tests for highlight of records, spec, behaviour and more

src/els_parser.erl
=> [#844] Do not crash if atoms are used as a compiler directive

src/els_app.erl
In #660 we switched from `elvis` to `elvis_core`, but we were still
configuring the old application.
Fixes #700 .
=> [#700] Silent Elvis during tests

src/els_compiler_diagnostics.erl
In case module was compiled with the 'deterministic' flag, the compile_info key does not have the 'option'  part so it is 'undefined'
Fixes # 
'undefined' is treated as a list and used with ++ that crashes els_compiler_diagnostics:load_dependencies(317).
=> Dont crash in case compiler option is not found in a beam

src/els_dodger.erl, test/els_rename_SUITE.erl
The dodger used to replace a macro with a local function call. That works in
expressions but not in patterns like function heads or catch patterns. Instead
of a function call a tuple syntax is used which works in more places.
(`?MACRO(Arg1, Arg2)` is temporarily replaced by `{'a-magic-atom', MACRO, Arg1, Arg2}`
instead of old `'a-magic-atom'(MACRO, Arg1, Arg2)`)
This change is motivated by the commonly used `?EXCEPTION` macro
```
try
...
catch
?EXCEPTION(Class, Reason, StackToken) ->
...
end.
```
Open source examples:
https://github.com/devinus/poolboy/commit/5d40cc517edc9bb8ee70756544167b63f66662f0
https://github.com/eproxus/meck/commit/558e925b48ce257b12e381080c851dc49c87d7bb
I only noticed when looking at the tests that there is already a ticket which is addressed by this change:
Fixes …
=> Handle macros in patterns

test/els_test_utils.erl
Just a minor cleanup in test. Additionally the [Internals](https://erlang-ls.github.io/internals/) page also talks about Mnesia. Maybe that page could be deleted or just mention the database is only stored in memory?
=> db_dir env var is not used any more

src/els_config.erl, src/els_elvis_diagnostics.erl
Added option for configuring elvis config path
=> Provide elvis_path option

src/els_rename_provider.erl, test/els_rename_SUITE.erl
The range of a macro poi includes the leading '?'. However the columns were not
converted to protocol-range, so the values were shifted one char to the right
resulting in the '?' being preserved but the char after the macro being deleted.
=> Fix macro rename deleting the next character

src/els_compiler_diagnostics.erl, src/els_config.erl, src/els_config_runtime.erl, src/els_distribution_server.erl, src/els_utils.erl, test/els_diagnostics_SUITE.erl
Add use_long_names boolean variable to erlang_ls.config
Add cookie string variable to erlang_ls.config
This change will allow using long node names for the runtime node
=> Implement using long names for distribution

Makefile
The `suggest_spec` test fails if the appropriate PLT does not exist.
Update the makefile so that `make ci` builds the PLT, so the tests can be run
locally and pass.
=> Update Makefile to build needed .plt for typer tests

.github/workflows/build.yml
Leaving '*' instead of 'main' only to be able to run CI *before*
opening a PR.
Fixes #869 .
=> [#869] Avoid un-necessary CI runs

priv/code_navigation/src/diagnostics_bound_var_in_pattern.erl, src/els_bound_var_in_pattern_diagnostics.erl, src/els_diagnostics.erl, test/els_diagnostics_SUITE.erl, test/els_test_utils.erl
Inspired by the infamous "pinning operator" and the great blog post of Roberto
on how to write a diagnostics backend. The backend is disabled by default
because of the mixed feedback the pinning-operator idea received.
=> Add diagnostics highlighting already bound variables in patterns

src/els_indexing.erl
They take up a lot of memory, duplicated for each project, and most of them not
used. They will be reloaded and inserted when needed by calling
`els_utils:lookup_document/1` so there is no information loss.
OTP modules are outside of the project root, so for example if one jumps to the definition of an OTP function and opens an OTP module it will start a new ELS node. Hence the POIs of OTP modules in a non-OTP project are mostly unused. (One exception I noticed when showing hover-docs, it fetches the function heads and so it currently loads and stores the module again) 
This is just a quick fix - On the long term there could be a different, limited set of info stored for OTP modules, only those which are for referencing but nothing that is about the implementation.
I observed the below …
=> Don't store the pois of OTP modules in ets at startup

src/els_dap_general_provider.erl
We don't need to keep the bindings for scopes stored after they have been queried.
=> [dap] remove cached sub-scopes when querried

src/els_dt_references.erl, src/els_references_provider.erl, test/els_references_SUITE.erl
Finding references when pointer is on the first clause works, because element at
position is a `function` POI. However when the pointer is on another clause of a
multi-clause function, element at position is a `function_clause` POI.
=> Support references from function_clause POI

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl, apps/els_lsp/test/els_references_SUITE.erl
Use the generic fold and subtree mechanism to descend into nested structures and
find all types and record types.
I started out fixing jumping to type and record definitions from record definitions. Then a bit of scope creep happened, as I realised the body of type and spec attributes used to be parsed on a special shallow way only. Additionally I made preparations to find macros in all kinds of weird places in attributes.
Fixes #815 #818 even more
=> Find POIs recursively in type, spec and record attributes

apps/els_dap/src/els_dap_general_provider.erl
It's not possible to have fully-fledged expressions through the interpreter in the watch list:
- each evaluate through the meta process triggers an update to the stack frame
- an update to the frame triggers an update to the watch list (which triggers an update to the frame)
This limits this to extracting variables from the current frame, similar to hover. There are some potential things we can do, e.g. erl_eval in the project node, but it's an easy way to break the DAP.
I'll revisit this when working on the REPL.
=> [dap] limit the watch list to variables in the current frame

apps/els_lsp/src/els_completion_provider.erl
Erlang/OTP 24 starts to warn when a \_Variable is used in a match, so we remove the '_'. See https://github.com/erlang/otp/pull/2995 for details about the warning.
=> Fix Erlang/OTP 24 compiler warning

apps/els_core/src/els_dodger.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
`erl_syntax:attribute_arguments` returns the AST of AST for type attributes. (See details in code comments) That is problematic in multiple places:
- `els_dodger` can't properly find and rewrite magic-macro-tuples because it will see the AST of the AST of these tuples. It still used to add fallback macros.
- then `erl_syntax:concrete` only handles an AST of a term, it crashes if the input includes AST of macros (or types). [`erl_syntax_lib:analyze_wild_attribute` ](https://github.com/erlang/otp/blob/master/lib/syntax_tools/src/erl_syntax_lib.erl#L1604) uses that and also fails.
Because els forked the dodger we have the freedom to return different representation for type attributes. But that needs to be handled in els_parser as well.
New representation of args are: ([erl_parse abstract …
=> Handle macros in type attributes

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
The infinite loop was triggered during indexing OTP by [`syntax_tools_SUITE_data/syntax_tools_test.erl`](https://github.com/erlang/otp/blob/master/lib/syntax_tools/test/syntax_tools_SUITE_data/syntax_tools_test.erl#L17) containing
```
-?attrib([foo2/2]).
```
While running the indexing on OTP I also found that a macro in a spec name caused a crash preventing parsing the whole file.
This was revealed by another test file in syntax_tools (`syntax_tools_SUITE_data/type_specs.erl`) containing
```
-spec ?MODULE:b() -> integer() | t().
```
Fixes #919
=> Fix infinite loop when parsing macro in wild attribute name

apps/els_core/src/els_distribution_server.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_rpc.erl, apps/els_dap/test/els_dap_general_provider_SUITE.erl
- shutdown dap and send events when project node goes down
- ensure, that we don't double monitor nodes
- shutdown project node when we get a disconnect request
- add config for cookie and startup timeout
=> [dap] improve dap startup and shutdown

apps/els_lsp/priv/code_navigation/src/diagnostics_autoimport.erl, apps/els_lsp/priv/code_navigation/src/diagnostics_autoimport_disabled.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
Add indexing of no_auto_import compile options. Use this information when deciding whether a fun reference is to a BIF.
Fixes #860.
=> Make els_code_navigation find non-fully qualified BIFs

apps/els_core/src/els_text.erl, apps/els_lsp/priv/code_navigation/src/hover_docs_caller.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/els_references_SUITE.erl
The `spec` POI has no data value any more. Hopefully it was not used elsewhere.
Fixes #922
=> Fix extracting function spec snippets

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
Each `function_clause` POI contains the pretty printed text of the function head
and guards. The pretty printing used to crash if any of those contained unicode
characters.
Found while running indexing through all of OTP. I am afraid this is just one spot, as source code is handled as list of bytes in many places, but Im not an expert in unicode and source code encodings and printable ranges and friends.
=> Handle unicode in function clauses when pretty printing

apps/els_core/src/els_utils.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_crossref_diagnostics.erl, apps/els_lsp/src/els_diagnostics_utils.erl, apps/els_lsp/src/els_folding_range_provider.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/src/els_unused_macros_diagnostics.erl
Use els_utils:lookup_document for document lookups to make sure that files that were not yet indexed are indexed on request. Related to https://github.com/erlang-ls/erlang_ls/pull/881
Fixes #928
=> Use els_utils:lookup_document for lookup

apps/els_dap/src/els_dap_breakpoints.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/test/els_dap_SUITE.erl, apps/els_dap/test/els_dap_general_provider_SUITE.erl
This implements debugger based logpoints and fixes the watchlist.
Logpoints don't stop but instead print a message on the console. In practice this is an additional field for the breakpoint.
This implementation
- breaks on the breakpoint
- evaluates the expression
- creates an output event for the console
- continues
Evaluation triggers the callback from the attached project and that was exactly what was messing with the watch list as well. (and this is fixed as a side-effect)
=> [dap] add logpoints and fix watchlist

apps/els_lsp/src/els_dt_document.erl
This table stores .erl/.hrl module's plaintext contents; it compresses very well
I haven't noticed any performance impact. If we don't do "fullscan" types of queries over this table (so, only key-value lookups), it should be very efficient.
Before:
```erlang
> memory().                                      
[{total,251125176},
{processes,30997488},
{processes_used,30995808},
{system,220127688},
{atom,2359705},
{atom_used,2344780},
{binary,27809064},
{code,11710823},
{ets,166721104}]
> [{K, V / 1024.0 / 1024} || {K, V} <- memory()].
[{total,239.54800415039063},
{processes,29.617919921875},
{processes_used,29.61713409423828},
{system,209.93008422851563},
{atom,2.25039005279541},
{atom_used,2.236156463623047},
{binary,26.52086639404297},
{code,11.16831111907959},
{ets,158.9976348876953}]  % …
```
=> Let dt_document be a compressed ETS table

apps/els_lsp/src/els_bound_var_in_pattern_diagnostics.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/src/els_unused_macros_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_initialization_SUITE.erl
This commit enables a few diagnostics which have been considered
experimental for a while, but they proved to be quite stable:
* bound_var_in_pattern
* unused_includes
* unused_macros
Fixes #941 .
=> [#941] Enable diagnostics by default

apps/els_lsp/test/prop_statem.erl
In b0ca70f the config file that is used in the PropEr tests was renamed, causing the warning logs described in the issue. This commit renames the file back to `erlang_ls.config`.
Partially fixes #921 (as I locally now get crash reports from Erlang LS, but the property still holds).
=> [#921] Fix wrong config file in PropEr tests

apps/els_lsp/src/els_code_lens.erl, apps/els_lsp/src/els_code_lens_ct_run_test.erl, apps/els_lsp/src/els_code_lens_server_info.erl, apps/els_lsp/src/els_code_lens_show_behaviour_usages.erl, apps/els_lsp/src/els_code_lens_suggest_spec.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_providers_sup.erl, apps/els_lsp/src/els_typer.erl, apps/els_lsp/test/els_execute_command_SUITE.erl
Instead of showing an "Add spec" button for missing spec, preview the
actual calculated spec by TypEr. Also:
* Simplify the `els_code_lens` behaviour
* Add an optional `init` function for the lenses
* Relax supervision strategy
Fixes #899 .
=> [#899] Self-describing specs.

apps/els_core/src/els_client.erl, apps/els_core/src/els_provider.erl, apps/els_lsp/src/els_code_lens_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_server.erl, apps/els_lsp/test/els_server_SUITE.erl
* Add a `$_cancelRequest/0` to the `els_client` to cancel the last issued request
* Handle cancellation requests, instead of ignoring them
* Add optional `cancel_request/2` callback for providers
* Execute `codeLens` requests in a separate process via `els_background_job`
* Implement cancellation for `codeLens` requests
* Add a minimal test
While implementing this, I noticed a bunch of possible refactoring and simplifications when it comes to `els_server`, `els_methods` and `els_provider`, but those will be tackled separately.
Fixes #950, #952.
=> [#950] Be able to cancel codeLens requests

apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/test/els_completion_SUITE.erl
Limit completions in `-export()` and `-export_type()` to unexported definitions
=> Limit export completions to unexported definitions

apps/els_lsp/priv/code_navigation/src/rename_variable.erl, apps/els_lsp/src/els_range.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_rename_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
Add support for renaming a variable in the scope of a function clause.
=> Add support for renaming variables

.github/workflows/build.yml, apps/els_core/src/els_escript.erl, apps/els_core/src/els_text.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/src/els_range.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_document_highlight_SUITE.erl, rebar.config, rebar.config.script
This PR adds rudimentary support for giving error location information based on the column number returned by the erlang compiler.
This PR depends on https://github.com/erlang/otp/pull/2664 and https://github.com/erlang-ls/erlang_ls/pull/832.
I decided to use the poi that the column is pointing to as the object to mark as the compiler only emits the starting column and not the end column.
Using the poi is not ideal as sometimes it can select a much larger section than it should, the most obvious example is when an attribute is broken somehow. It is however better than trying to come up with some other heuristic about which range it is that is responsible for the warning.
I've put this PR as a draft as I'm not happy about the usage of `poi`s. So I'm looking to see if anyone has any better …
=> Add column numbers

apps/els_lsp/priv/code_navigation/src/hover_macro.erl, apps/els_lsp/src/els_docs.erl, apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
Show macro definition on hover.
We now store the define value in the POI, this should be helpful when implementing #829.
=> Show macro definition on hover

apps/els_core/src/els_provider.erl
Whenever a provider (typically the `lens` one) is busy, the cancellation request can time out, causing a crash in `els_server`. At that point the response to the cancellation request is not sent and the client is stuck. Instead, deal with the cancellation request asynchronously.
Fixes #976 .
=> [#976] Cancel requests asynchronously

apps/els_lsp/priv/code_navigation/src/diagnostics_bound_var_in_pattern.erl, apps/els_lsp/src/els_bound_var_in_pattern_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
This is a workaround for erl_syntax_lib not considering shadowing in fun
expressions.
There is a further issue with named funs where variables from the name and head
are not added to the env of the fun body. This is not fixed by the current
change.
Fixes #982.
=> Fix bogus bound variable warnings in fun expression heads

apps/els_lsp/src/els_definition_provider.erl, apps/els_lsp/test/els_definition_SUITE.erl
This is inline with what most other LS are doing, when we jump-to-definition on a definition (or no definition can be found), try to return references instead. If there are no references, give up.
=> return references if no definitions are found

apps/els_dap/src/els_dap_breakpoints.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/test/els_dap_general_provider_SUITE.erl, elvis.config
This PR adds basic support for **conditions** and **hitconditions** for break/logpoints in the debugger ([see specification](https://microsoft.github.io/debug-adapter-protocol/specification#Types_SourceBreakpoint)).
**Details**
- A break/logpoint with a **condition** only triggers if the condition expression **evaluates to true**.
- Hitconditions currently must be non-negative integers N, meaning that only **every Nth hit** of a break/logpoint will trigger.
- Note that it is possible to have both a condition and a hitcondition for a break/logpoint, in this case we are only counting hits where the condition is true, and we only trigger at every Nth such hit.
- Note that conditions and hitconditions work the same way both for breakpoints and logpoints. The only difference is that …
=> [dap] Add basic support for break/logpoint (hit)conditions.

apps/els_lsp/src/els_execute_command_provider.erl
Until this lens is disabled (if decided) this allows to click it without
anything bad happening.
Fixes #991 .
=> [BUGFIX] fix function-references lens, issue #991

apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_rename_SUITE.erl
Previously functions could only be renamed when pointing at the definition, now a function can be renamed when  pointing at a reference too.
=> Allow renaming function when pointing at function reference

README.md
Add missing description to show how to install erlang_ls once `make` was done.
=> Show how to install erlang_ls

apps/els_lsp/src/els_code_lens_suggest_spec.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_typer.erl
also use empty command with a spec lens when failed to extract spec
The only editor that seem to be affected is Emacs. When suggested spec is too long it is wrapped over multiple lines in the editor window. In vim (coc) and Vs Code it is always presented as one very long line. Nonetheless it is probably good to avoid arbitrary long lens titles. This truncates the title to 100 chars by default (the font of the lens is typically smaller than normal text, hence it can be more than 80 chars).
Also fixes a bug when TypEr fails and no spec is available the lens with the error message was still clickable and would be producing a new line of text.
Fixes #960 and #995 .
=> [FEATURE] truncate suggested spec title

apps/els_lsp/src/els_dialyzer_diagnostics.erl
Dialyzer diagnostics crashes with bad arith on OTP 24.
Seems like this was broken in OTP 24 as the warning now returns a line and
column. Use `erl_anno:line/1` which will handle both `Line` and `{Line, Col}`
Side note: Seems like there are no tests for dialyzer diagnostics.
=> Properly extract line number from dialyzer warning

apps/els_core/src/els_utils.erl, apps/els_lsp/priv/code_navigation/src/code_navigation_undefined.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/src/els_scope.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_references_SUITE.erl, apps/els_lsp/test/els_rename_SUITE.erl, apps/els_lsp/test/els_test_utils.erl, apps/els_lsp/test/els_workspace_symbol_SUITE.erl, elvis.config
References are only searched in the document containing the definition and
documents that (maybe recursively) include the defining document. The scoping
for macro and record referencing is also changed to the same.
=> Support record fields in reference provider

apps/els_lsp/priv/code_navigation/include/definition.hrl, apps/els_lsp/priv/code_navigation/src/code_navigation_types.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_references_SUITE.erl
Finding references of type definitions in header files didn't show references in source files that included the header.
This should now be fixed.
Based on the similar fixes for records in #1001.
=> Fix find references for included types

apps/els_core/include/els_core.hrl, apps/els_core/src/els_config.erl, apps/els_core/src/els_text.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_index_buffer.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_sup.erl, apps/els_lsp/src/els_text_synchronization.erl, apps/els_lsp/test/els_text_SUITE.erl, elvis.config
Implement support for incremental text synchronization.
This should improve the experience when editing large files since we no longer need to transmit the entire text buffer for every change, instead a set of changes are submitted and applied.
To avoid triggering indexing for every update I've added `els_index_buffer` which will accumulate changes and index the accumulated result of the changes.
This feature is disabled by default but can be enabled by adding the follwing line to erlang_ls.config:
```yaml
incremental_sync: true
```
I've only tested these changes with Emacs lsp-mode.
Would be great if people with other editor setups could also test it out.
=> Implement support for incremental sync

apps/els_lsp/priv/code_navigation/src/code_navigation.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_definition_SUITE.erl, apps/els_lsp/test/els_parser_SUITE.erl
Macro name should be identified by both name & arity (if available).
Macros can be overloaded on arity. Currently, if that happens, the
navigation is incorrect and points to the first definition with
particular name, regardless of the actual arity.
=> Fix navigation to macros with overloaded arity

README.md, apps/els_core/src/els_config.erl
This PR allows erlang-ls users to call their configuration files `erlang_ls.yml` instead of `erlang_ls.config` to avoid mixing them up with config files, as in AdRoll/rebar3_format#259
=> Allow config files to be called erlang_ls.yaml

apps/els_core/src/els_uri.erl
Fix file path on Windows, replace `%3A` to `:`.
Fixes #963 and erlang-ls/vscode#54 .
=> Fix file path on Windows

apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_rpc.erl
Different from "launch" which will start a shell, "attach" will attach to an existing shell.
See https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Attach
Add handle_request for "attach"
Change handle_request for "disconnect" if it was "attach" don't stop the node, only stop breakpoints.
Tests see comment.
Fixes # .
=> [dap] support "attach"

apps/els_dap/src/els_dap_general_provider.erl
Clients may send a pause request, and there is no capability that negotiates these. The OTP debugger does not have a notion of pausing a running execution and the DAP currently crashes when someone presses pause.
This implements a noop pause handling.
=> [dap] dummy handler for pause

apps/els_lsp/priv/code_navigation/src/completion_incomplete.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
The unexpected atom (an incomplete function name) in the export attribute caused
the below crash in the parser. This way the completion provider failed to
determine that the location is in an export context, and used function snippet
with arguments instead of '/arity'.
For example when hitting enter on a completion erlang_ls used to insert
`foo(Arg)` instead of `foo/1`.
```
1> els_parser:parse("-export([foo]).").
2021-06-06T16:40:30.522244+02:00 warning: Please report error parsing form error:{try_clause,foo}:[{els_parser,'-skip_function_entries/1-fun-0-',1,[{file,"/Users/ext.pgomori/git/erlang_ls/apps/els_lsp/src/els_parser.erl"},{line,839}]},{lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1286}]},{els_parser,attribute_subtrees,2,[{file,"/Users/ext.pgomori/git/erlang_ls/apps/els …
```
=> Fix regression: completion for incomplete export enrty

apps/els_lsp/priv/code_navigation/src/implementation.erl, apps/els_lsp/priv/code_navigation/src/implementation_a.erl, apps/els_lsp/priv/code_navigation/src/implementation_b.erl, apps/els_lsp/src/els_implementation_provider.erl, apps/els_lsp/test/els_implementation_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
Using the info from the DB, we can "jump to implementation" for callback functions. This can be especially useful in presence of _optional_ callbacks which only certain modules implement.
For example, the `els_code_lens` behaviour is used in 5 modules, but only 2 of them implement the `precondition/1` callback:
`lsp-find-implementation`
Fixes #1031 .
=> [#1031] Find implementations for callback functions

apps/els_lsp/include/els_lsp.hrl, apps/els_lsp/src/els_background_job.erl, apps/els_lsp/src/els_log_notification.erl, apps/els_lsp/src/erlang_ls.erl
* Use timestamp as first entry
* Move message to the front to improve readibility (left-alignment for
messages)
* Remove un-necessary new lines
* Rename ELP -> LSP
* Remove redundant pid from Background job log messages
* Use macros instead of numeric literals for message types
* Shorten mapping function name
=> [#992] Cleanup logging

apps/els_lsp/priv/code_navigation/src/diagnostics_unused_macros.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl, elvis.config
If we don't create a POI for a function application (because module or function is not a literal atom) then potentially create POIs from its subtrees.
Fixes #1021  .
=> Fix creating macro POIs in function applications

apps/els_lsp/priv/code_navigation/include/transitive.hrl, apps/els_lsp/src/els_diagnostics_utils.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_fungraph.erl, apps/els_lsp/src/els_scope.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/test/els_fungraph_SUITE.erl
Before this commit recursion in `els_scope:included_pois/2` might become infinite. This can happen for a couple of reasons:
* header mistakenly includes itself,
* header ends up including itself transitively, though inclusion is guarded with `ifndef` and `define` to prevent compiler from
complaining.
* header includes another header with exactly same filename but  located in a different directory, yet from the point of view of  `els_utils:find_header/1` it's the same header.
This commit introduces simple abstract functional graph concept with traversals over set of nodes reachable from a given node and employs it to gather all POIs reachable through inclusion in the `els_scope` module.
=> Prevent infinite recursion when enumerating document POIs

apps/els_lsp/priv/code_navigation/include/hover_record.hrl, apps/els_lsp/priv/code_navigation/src/hover_record_expr.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_docs.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
With this change you can hover over a record expression, and get a definition of the record.
=> Add support for hover on record expression.

apps/els_core/src/els_text.erl, apps/els_lsp/test/els_text_SUITE.erl
Use `els_utils:to_binary/1` instead of `iolist_to_binary/1` to ensure proper unicode handling when applying text edits.
Fixes #1039
=> Fix crash when applying edits to unicode text

apps/els_core/src/els_config.erl
One of the most common issues among new Erlang LS users is the lack of a configuration file. This simple change shows a warning to the user whenever a config file is not found for a project, pointing to the relevant documentation. This should simplify the user experience for new users.
=> [#990] Show warning to the user in case of missing config file

apps/els_core/src/els_config.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_lsp/src/els_general_provider.erl
A more appropriate solution, removing the dependency on the els_config module, will be provided separately.
=> [#1060] Quick fix for the DAP regression

apps/els_dap/src/els_dap_general_provider.erl
In Emacs, the events were not displayed in the UI otherwise.
=> Specify category for DAP events

apps/els_dap/src/els_dap_general_provider.erl
The continue requests reponse defines an optional `allThreadsContinued` field
that defaults to true. This breaks the DAP when debugging multiple threads.
The solution is simple, set allThreadsContinued to flase when responding to the continue request.
Fixes #1068
=> [dap] fix continue request response

apps/els_core/src/els_distribution_server.erl
This fixes a recently introduced regression. The `erlang:get_cookie/0`
was moved earlier, to a stage where distribution was not started
yet. Since that function returns `nocookie` in a system with no
distribution, that caused the atom `nocookie` to be erroneously used
as a cookie. A cleaner approach could be used, but that would require
a bit of refactoring. For now this should fix the regression with
minimal code changes.
Fixes #1070 .
=> [#1070] Only set the cookie if the provided one is a valid one

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
A new option is added to the configuration (exclude_unused_includes).
Header files specified by this configuration option are not checked weather
they are used or not.
Workaround for  #1047  and #964.
=> Add config option to exclude unused headers from warnings.

apps/els_lsp/priv/code_navigation/src/diagnostics_unused_macros.erl, apps/els_lsp/src/els_unused_macros_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
Fixes `badarg` in `els_unused_macros_diagnostic` thrown when unused macro has parameters. 
Error looks like this in Sublime-LSP LSP log:
:: <-  erlang-ls-debug window/logMessage: {'type': 1, 'message': '[2021-08-24T19:09:15.983514+03:00] [error] crasher: initial call: els_background_job:init/1, pid: <0.211.0>, registered_name: [], error: {badarg,[{erlang,atom_to_binary,[{\'D\',1},utf8],[]},{els_unused_macros_diagnostics,make_diagnostic,1,[{file,"/home/nwalker/pg/erlang_ls/apps/els_lsp/src/els_unused_macros_diagnostics.erl"},{line,64}]}, <SKIPPED>, ancestors: [els_background_job_sup,els_sup,<0.159.0>], message_queue_len: 0, messages: [], links: [<0.181.0>], dictionary: [], trap_exit: true, status: running, heap_size: 10958, stack_size: 28, reductions: 49101; neighbours: …
=> Fix type mismatch in unused_macros diagnostic.

apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
Expose the module and error passed to `Module:print_error` as an error code.
This allows us to provide telemetry of the codes, for later analysis, in
situations where this is practical.
It also allows an easy tie-up to any external documentation about how to deal
with the error.
The mechanism is to use the source of the original `format_error/2` clauses to map
onto codes, which have a regular format, e.g. `L1227` where the first letter
indicates the linter, and the rest is just a 4 digit unique number.
This format fits in with with existing error presentation in IDEs, as it is
already used by other compilers such as rust.
=> Introduce diagnostic codes for the OTP compile

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
When enabled, send a `telemetry/event` notification containing the URI and error codes for compiler diagnostics in the given file.
The allows analysis of diagnostics type prevalence if the client logs it.
It is disabled by default.
This PR depends on #1078 .
=> Send telemetry notification with compiler diagnostic codes

apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_rpc.erl
This makes the els_dap_rpc try much harder to find the source, by first
asking `int:file/1`, then `code` and `filelib:find_source/1` and
finally falling back to the current behaviour of using `module_info`
and checking the `source` compilation option.
This allows you to build dependencies/OTP in one place, and run it from
another.
=> Fix DAP not finding the source for a module

.github/workflows/build.yml
CI fails due to this step. Let's skip it for now, until a fix is found. We may even consider dropping coveralls altogether and use some other solution, since reports do not seem correct anyway.
=> [#1086] Temporarily skip coveralls send

apps/els_lsp/priv/code_navigation/src/diagnostics_unused_includes_compiler_attribute.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
Fixes #964 and partially #1047.
=> [#1047] Mark headers with compiler attributes as used

apps/els_lsp/src/els_elvis_diagnostics.erl
In case of an issue with the `elvis.config` (e.g. when using an undefined rule), the Elvis backend crashes instead of reporting a regular diagnostic. This PR ensures that config errors are also displayed to the user as Diagnostics. We should probably add diagnostics for the `elvis.config` file itself, but this should be an improvement. Since config errors do not correspond to a specific line in the open buffer, I'm arbitrarily reporting them on line 1.
=> [#1067] Handle Elvis config errors

apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_methods.erl
When cmd+click on a function (or similar) in a large document, the client might produce the following requests:
- hover request (when having the mouse over the element)
- cancel request (when clicking)
- definitions request
The hover request can take several seconds, and is synchronous currently. All actions that follow the hover request are stalled until it is served. This change uses background jobs for hover instead, which makes them cancellable and provides lower latencies for follow-up requests, e.g. definitions.
=> user background job for hover provider to avoid blocking request queue

apps/els_lsp/priv/code_navigation/src/diagnostics_unused_record_fields.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/src/els_unused_record_fields_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_initialization_SUITE.erl, apps/els_lsp/test/els_test_utils.erl
=> [#1098] Detect unused record fields

apps/els_core/src/els_config.erl
Test data directories may contain erlang files with modules names
that clashes with application or system modules, ignore these
directories.
As one example in otp "lib/dialyzer/test/r9c_SUITE_data/src/" contains
the many files that clashes. This causes among other things that
jump to definition almost always jumps to the wrong place when working
inside OTP.
Fixes #859
=> [#859] Ignore test data directories.

apps/els_core/src/els_utils.erl
Avoids double recursion, recursion is done in els_config.
This fixes #859 which my previous PR failed to do.
From what I can see els_util:fold_files is only used for indexing and input 
data are the directories from els_config which have already been recursed once.
=> Do not recurse in els_utils:fold_files

apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_test.erl
After this cleanup and refactoring, a typical diagnostics suite will look like:
```
-spec escript_warnings(config()) -> ok.
escript_warnings(_Config) ->
Path = src_path("diagnostics_warnings.escript"),
Source = <<"Compiler">>,
Errors = [],
Warnings = [ #{ code => <<"L1230">>
, message => <<"function unused/0 is unused">>
, range => {{23, 0}, {24, 0}}
}
],
Hints = [],
els_test:run_diagnostics_test(Path, Source, Errors, Warnings, Hints).
```
Fixes #1128 .
=> [#1128] Refactor test framework for diagnostics

.github/workflows/build.yml, README.md
Fixes #1086. The authentication warning reports are still there, that's related to some SSL in OTP 24, but the issue with `coveralls` seemed to be a hiccup on their end and not a problem in ours.
=> Bring back `coveralls send` step in CI

apps/els_core/src/els_stdio.erl, apps/els_lsp/src/els_eep48_docs.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_hover_SUITE.erl
Fix problem with unicode output to stdout.
While at it also improve rendering of definition lists with code blocks in them.
Closes #1145
=> Fix unicode output via stdout

apps/els_core/src/els_stdio.erl
The support to render unicode broke the latin1 support so until we fix both we fall back to latin1 so that we can open such files...
People really should update their files to be unicode!
For anyone wondering how to update latin1 files to unicode:
```erlang
convert(Filename) ->
{ok, Latin1} = file:read_file(Filename),
file:write_file(Filename, unicode:characters_to_binary(re:replace(Latin1,"coding: latin-1",""), latin1, unicode)).
```
=> Revert unicode support

apps/els_lsp/priv/code_navigation/src/diagnostics_module_name_check.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
=> [#1152] Emit error in case the module name does not coincide with the filename

apps/els_lsp/src/els_server.erl
=> [#1050] Add separate way to send log notification to avoid recursion

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_diagnostics.erl
Little optimization to avoid re-computing the list of enabled diagnostics at every request.
=> Precompute list of enabled diagnostics

misc/dotemacs
=> [#1174] [emacs] Ensure keybinding is configured before loading lsp-mode

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
erlfmt_parser returns a `raw_string` form for comments which are after the last
form in the file and not followed by any more form. It was not expected by
els_parser that a raw_string can contain no tokens (just comments and
whitespace). A file with no code just whitespace has the same result.
Fixes #1171
=> Fix parsing trailing comments in modules

apps/els_lsp/priv/code_navigation/src/rename_variable.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_rename_SUITE.erl
Tweak the heuristic for variable renaming inside functions so it doesn't bleed over to following -spec.
Add possibility to rename variables in specs.
Fixes #1180.
=> Fix issues with rename variable involving specs

apps/els_core/src/els_config_runtime.erl, apps/els_core/src/els_distribution_server.erl
This fixes an issue where initialization of els distribution would fail
due to invalid node name if the project directory contains characters
that are not valid in an erlang node name.
=> Ensure that default node name is valid

apps/els_lsp/priv/code_navigation/src/rename_variable.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl, apps/els_lsp/test/els_rename_SUITE.erl
Argument variables POIs weren't parsed in macro definition.
This PR fixes that.
Fixes comment in https://github.com/erlang-ls/erlang_ls/pull/1183#discussion_r795205932
=> Fix parsing of define arguments

Makefile, README.md
Allows the user to install the built package into a different directory than `/usr/local` by setting the `PREFIX` environment variable.
```sh
PREFIX=/usr/local/stow/erlang_ls-0.21.2 make -e install
```
I want to keep my manually installed packages easy to upgrade and remove, so I use [GNU Stow](https://www.gnu.org/software/stow/) for that purpose. I install the package to `/usr/local/stow/<name>` (where `<name>` is some arbitrary name I chose), then have Stow create symlinks into `usr/local`. Stow owns these symlinks and if I want to remove or replace a package it knows exactly which symlinks to remove.
This is much better than having a number of files from various packages lying all around the system. erlang_ls is not bad, it has only two files, but even two files here and two files …
=> Allow installing into custom directory

apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/src/els_scope.erl, apps/els_lsp/test/els_definition_SUITE.erl, apps/els_lsp/test/els_rename_SUITE.erl
Improve goto definition for variables
* Use same scoping rules as variable renaming
* No longer limited to only variables inside functions
* Add support for finding variable references
=> Improve goto definition for variables

apps/els_lsp/src/els_compiler_diagnostics.erl
Invalid syntax on the module attribute can cause a crash.
=> Avoid compiler_diagnostics crash in case module name is invalid

apps/els_lsp/priv/code_navigation/src/rename_module_a.erl, apps/els_lsp/priv/code_navigation/src/rename_module_b.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_rename_SUITE.erl
Add support for renaming modules.
Put cursor at modname in `-module(modname)`, and trigger the rename command.
This will rename the .erl file (in the same directory), updated the -module attribute 
and update references to the module such as:
* Function applications 
* Type applications
* Implicit functions
* Imports
* -behaviour attributes
This PR also improves the "find references" functionality for modules, previously it only displayed function references.
There's a small race condition with Emacs `erlang-mode` as it wants to be helpful and suggest that the old filename doesn't match the new module name, you need to answer no when it asks if it should fix the module name.
Personally I have now disabled that check:
`(setq erlang-check-module-name nil)` 
This feature could be handled by …
=> Add support for renaming modules

apps/els_core/src/els_uri.erl, apps/els_lsp/priv/code_navigation/src/diagnostics module name check.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
Fix false positive module name check diagnostic
Discovered that modules with whitespace in their name could cause false
positives in the module name check diagnostic.
Root cause is in els_uri:path/1, since uri_string:normalize/1 return a percent
encoded path, we need to percent decode that path to get the real path.
=> Fix handle module name whitespace

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_diagnostics.erl
This reverts commit 2f6decd8cfe342da60e102b55cde66c4af7f784a.
This change introduced a regression in the debugger, preventing it from starting.
The `els_dap` escript invokes the `els_config` initialization procedure
(see https://github.com/erlang-ls/erlang_ls/commit/4b475b0864f433ccc08c80609478f5b15b9b41b7),
but the new version of the initialization depends on the `els_diagnostics` module,
which is part of the `els_lsp` application, not included in the `els_dap` escript.
For now simply reverting the change, but we should revisit the application structure.
The original idea was for an application to contain the implementation of the JSON-RPC protocol
and for the `els_dap` and `els_lsp` to utilize that as a dependency. That never really happened
and the current application split in Erlang …
=> Revert "Precompute list of enabled diagnostics"

apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_rename_SUITE.erl
The textDocument parameter in a TextDocumentEdit must contain a version, even if null (see the OptionalVersionedTextDocumentIdentifier definition from the LSP specification). Without it, some editors (most notably VS Code) would reject the edits.
=> Fix support for renaming modules

.github/workflows/build.yml, apps/els_lsp/priv/code_navigation/src/edoc_diagnostics.erl, apps/els_lsp/src/edoc_report.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/src/els_edoc_diagnostics.erl, apps/els_lsp/src/els_lsp.app.src, apps/els_lsp/test/els_diagnostics_SUITE.erl, apps/els_lsp/test/els_test.erl, elvis.config
This PR introduce support for [edoc](https://www.erlang.org/doc/apps/edoc/chapter.html) diagnostics.
There are a couple of limitations in the current `edoc` API:
* The list of errors and warnings is simply printed out using the `stdio` and not returned to the caller
* The process exits at the first error occurrence
An issue has been [created](https://github.com/erlang/otp/issues/5056) for the OTP team to address these.
The current solution (ab)uses the process dictionary, a fork of the `edoc_report` module and a try/catch to temporarily circumvent these limitations.
This diagnostics backend is disabled by default. To enable it, add the following to your `erlang_ls.config`:
```
diagnostics:
enabled:
- edoc
```
Fixes #384.
=> Edoc diagnostics

apps/els_core/src/els_utils.erl, apps/els_lsp/src/els_code_action_provider.erl
Fixes PR comment: https://github.com/erlang-ls/erlang_ls/pull/1212#discussion_r810965486
@michalmuskala
=> Use Jaro distance for the unbound variable code action

apps/els_lsp/priv/code_navigation/src/code_action.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_range.erl, apps/els_lsp/test/els_code_action_SUITE.erl
supply quickfix to remove unused macro
Fixes erlang-ls#882
=> supply quickfix to remove unused macro

apps/els_lsp/src/els_index_buffer.erl, apps/els_lsp/src/els_text_synchronization.erl
* didOpen: Handle indexing through els_index_buffer to avoid race
* didSave: Read and index file through els_index_buffer, this should introduce a
synchronization point if the index data has become out of sync.
Fixes some of the issues raised in #1220.
We still need to implement support for `didChangeWatchedFiles`
=> Safer incremental sync

apps/els_lsp/priv/code_navigation/src/code_action.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/src/els_range.erl, apps/els_lsp/src/els_unused_includes_diagnostics.erl, apps/els_lsp/test/els_code_action_SUITE.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
1. Send additional diagnostics to push data back to code actions.
2. Update tests.
Fixes #1202  .
=> Add Fix for #1202 remove unused include

apps/els_lsp/src/els_erlfmt_ast.erl, apps/els_lsp/test/els_parser_SUITE.erl, apps/els_lsp/test/els_parser_macros_SUITE.erl
=> Handle incomplete type definitions better

apps/els_lsp/src/els_elvis_diagnostics.erl
I noticed that elvis will set line number to 0 for the atom_naming_convention diagnostic, which results in ErlangLS sending -1 as line number to the LSP client. This makes at least VS code not show any other elvis diagnostics, even other diagnostics with valid line numbers.
This fix will set line number to 1 if we get 0 or below from elvis.
Will try to make a pull request to elvis_core as well to make it send an actual line number, but I think this precaution can still be good.
=> Avoid negative line numbers in elvis diagnostics.

rebar.config, rebar.lock
This updates Gradualizer to the tip of the current master branch, therefore brings in a number of fixes:
- https://github.com/josefs/Gradualizer/pull/383 - this prevents Gradualizer running in the ErlangLS BEAM instance from hogging CPU if it encounters some rare form causing the typechecker to fall into an infinite loop; in other words, it turns non-termination into a warning reported as any other diagnostic; overall, it greatly improves the UX and robustness
- https://github.com/josefs/Gradualizer/pull/384 - this fixes a bug where location of undefined/unexported types would be reported as line 0
- https://github.com/josefs/Gradualizer/pull/385 - this adds the Git commit sha to Gradualizer version, which makes comparing the behaviour of different builds much more convenient
- …
=> Update Gradualizer to the current master

apps/els_lsp/src/els_gradualizer_diagnostics.erl
The check to determine if project files should be imported into Gradualizer comes from the time when the integration relied on Gradualizer being available through ERL_LIBS and would only be started by the diagnostic being called.
Now that Gradualizer is a dependency of ErlangLS, it's running on each startup since ErlangLS itself. This means the check never succeeds, therefore the project specific files necessary for properly setting up the typechecker are never loaded. This leads to false positives being reported such as missing remote types or record definitions.
Reimporting the project files on each run might be a bit redundant, but it seems to work reasonably well in practice. Dogfooding this solution shows it doesn't lead to visible unnecessary load on the system.
=> Reload project-specific files on every Graudalizer diagnostic run

apps/els_core/src/els_distribution_server.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_methods.erl, apps/els_dap/src/els_dap_protocol.erl
This PR collects a number of fixes around DAP error handling.
* Exit code should be a number, not a string
* Do not silently crash DAP if distribution is not available
* Fix ErrorResponse format
* Show errors to users
* Increase severity of log messages for distribution shutdown errors
* Add missing clause to handle `ignored` answer from `net_kernel`
=> Improve DAP Error Handling

apps/els_lsp/src/els_docs.erl
Also make sure that functions dealing with temporary group leader here have no chance to get stuck altogether.
Fixes #1177.
=> Handle `not_found` result from docsh

apps/els_dap/src/els_dap.erl, apps/els_lsp/src/erlang_ls.erl
So that, in case of app crash, the whole node goes down.
=> Start apps as permanent

apps/els_lsp/src/els_background_job_sup.erl
To have the ability to terminate gracefully
=> Revert shutdown strategy for background jobs

apps/els_lsp/priv/code_navigation/src/folding_ranges.erl, apps/els_lsp/src/els_folding_range_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_call_hierarchy_SUITE.erl, apps/els_lsp/test/els_foldingrange_SUITE.erl
Moving folding_range from functions to a general field on each poi. Added support for records. Refactored support for functions. Added foldingrange_provider test
=> Refactor folding_ranges onto POIs, Add support for records.

apps/els_lsp/priv/code_navigation/src/code_action.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/test/els_code_action_SUITE.erl
Summary:
This fix supports adding a stub for the undefined function - T112182027
Test Plan:
The commit has a test case in the els_code_action_SUITE
Reviewers:
Roberto Aloi
Subscribers:
Nikita Rubilov
Tasks:
T112182027
Tags:
bootcamp_tasks
Fixes # .
=> Support for adding undefined Function

apps/els_lsp/src/els_db.erl, apps/els_lsp/src/els_db_server.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_dt_signatures.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_text_synchronization.erl
This PR introduce _versioning_ for documents, signatures and references. Versioning is available as part of the LSP specification. Versioning is currently supported by all major LSP clients (Emacs, VS Code, etc).
Whenever a module is indexed for the first time, the version is originally set to `null`. This allows the server to function even with LSP clients not specifying versions on change (but they will be exposed to all sorts of race conditions).
LSP clients, whenever sending a _change_ event for a document (`didChange`, `didChangeWatchedFile`), they normally include a version, which is guaranteed to be strictly incrementing (even if there can be gaps between two subsequent versions).
Whenever a change is detected, the language server immediately stores the new version of the text in …
=> Document versioning

apps/els_lsp/src/els_text_synchronization.erl
Without this change, the server could read an outdated version of the text from disk and
try to apply changes to it. This was a very common scenario in case a file was already opened
in the editor with pending changes, not yet saved to disk. A reload of the server would cause
the server to incorrectly rely on the version on disk.
The version is also used now, so that eventual background jobs on outdated versions of the code
would abort.
Fixes # .
=> Use version from didOpen, use text from editor as source of truth

apps/els_core/src/els_utils.erl
The Uri returned by the `shallow_index` procedure is reconstructed
from the path and could miss the query string originally contained in
the input Uri.
=> Handle query string in Uri

apps/els_core/src/els_utils.erl, apps/els_lsp/priv/code_navigation/src/hover_nonexisting.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/test/els_hover_SUITE.erl
If the user was hovering a fully qualified function for a non-existing module, the server would crash instead of showing no results.
=> Do not crash if module is not available while fetching specs

apps/els_core/src/els_provider.erl, apps/els_core/src/els_stdio.erl, apps/els_lsp/src/els_sup.erl
Since the main supervision strategy is rest_for_one, move the els_provider
process after the els_server one (restarting the els_server process currently
results in a node crash anyway). There is no need to restart the els_server
in case of els_provider failure, especially considering that the provider
process is the most likely to fail.
Also, give the provider a chance to cleanup on restart, by cancelling
pending jobs.
Finally, since it can now happen that, after a restart, the provider
receives messages (results or diagnostics) by background jobs, ensure
that such responses are handled correctly: results are propagated to
the server (no change) while diagnostics are ignored.
=> Solidify provider process

apps/els_core/src/els_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_server.erl, apps/els_lsp/test/els_references_SUITE.erl
It can happen that some files are opened in the editor. If these files
have pending changes (unsaved), we should consider them as the "source
of truth" when it comes to text edits flowing from the IDE to the
language server.
In case of an external operation (e.g. a checkout or rebase in a
version control system), Erlang LS inconditionally reloads changed
files from disk. This is an incorrect behaviour, since subsequent
operations applied via the IDE to a non up-to-date version of the
buffer can result in errors. The language server should ignore such
external operations when the file is opened in the editor.
Eventual inconsistencies between the disk-copy and the IDE-copy of the
file will be resolved in the context of the IDE (e.g. in VS Code the
user is warned about the situation on save) …
=> Track open files

apps/els_dap/src/els_dap_general_provider.erl
Same approach as for the LSP node, to avoid a crash if an existing DAP node is already running.
=> Add randomness to DAP node name

apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_text_synchronization.erl
According to [the specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen) the language server should not try to access the file from disk:
> The server must not try to read the document’s content using the document’s Uri.
Erlang LS erroneously does that. This can cause a server crash if the file is not available in the location specified by the Uri.
Using `app` as default source since the only side effect is to index references and signatures for the document, which is not a big problem if it is done also for a dependency or a file which is part of OTP.
Fixes #1296
=> Do not read file from disk on didOpen

.editorconfig, apps/els_lsp/priv/code_navigation/src/code_action.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/test/els_code_action_SUITE.erl
* Create function right after current function
* Create function with correct number of arguments
* Don't leave trailing whitespaces
* Don't create -spec
Fixes #1280
=> Improve create undefined function quick action

apps/els_lsp/src/els_typer.erl
the undocumented function dialyzer_succ_typings:analyze_callgraph/3 is not in OTP25.
use the (for the purpose of els_typer:get_type_info/1) equivalent
dialyzer_succ_typings:analyze_callgraph/5 when ?OTP_VERSION >= 25
fix #1304
=> fix els_typer on otp25

apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_text_synchronization.erl
It can happen during a rebase operation that a file appears/disappears
multiple times in a very short timeframe. Specifically, since
`didChangeWatchedFiles` notifications are asynchronous, it can happen
that a file is deleted before a notification is processed by the
server. In such a case, the server should simply ignore the
notification, since a new one will arrive.
Also, there is no need to deeply index files during a rebase, so let's
convert to a shallow indexing.
We mark the source of the file as 'app', which has the only side
effect of indexing references.
=> Avoid crash while reloading non-existing file

apps/els_lsp/src/els_dt_document.erl
The macro was returning an `ok`, which we were storing in the DB, causing a crash while extracting words.
Also raising log level from debug to warning.
=> Return set, log as an error

apps/els_lsp/priv/code_navigation/src/atom_typo.erl, apps/els_lsp/src/els_atom_typo_diagnostics.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
* Add diagnostics to catch misspellings of common atoms.
* Add code action to fix the typo
=> Add atom typo diagnostics

apps/els_lsp/src/erlang_ls.erl
Log files are not truncated by default, so users ended up with log files containing hundreds of MB. That's not necessary.
=> Truncate log file once it reaches 10MB, keep max 5 archive files

apps/els_lsp/src/els_background_job_sup.erl
Move from 5 restarts in 1 minute to 10 restarts in 10 seconds.
Background jobs are often not critical. This change should prevent
unnecessary node crashes.
=> Relax supervision max restart intensity

apps/els_lsp/priv/code_navigation/src/diagnostics_bound_var_in_pattern_cannot_parse.erl, apps/els_lsp/src/els_bound_var_in_pattern_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
The user was already not affected by these errors, since diagnostics
are computed as a background job, but this allows us to reduce the
noise in logs.
=> Degrade gracefully to no diagnostics if text cannot be parsed

apps/els_lsp/priv/code_navigation/src/diagnostics_unused_includes_broken.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
In case of incorrect syntax, it can happen that the content of an
include or include_lib is a tree and not a string. Since the
erl_syntax:string_value does not guarantee a string as the output,
let's explicitly validate the returned value. This will ensure that
non-string values are not stored in the DB, causing diagnostics to
fail due to wrong type assumptions.
=> Only store include/include_lib POIs as string

rebar.config
Version `1.1.0` of `rebar3_lint` dropped support or OTP 22 (see [this PR](https://github.com/project-fifo/rebar3_lint/pull/47)).
For the time being, let's just pin the linter version. FYI @elbrujohalcon @kdmnk.
=> Pin rebar3_lint version to be able to support OTP 22

apps/els_lsp/src/els_completion_provider.erl
Sometimes completion stops working due to the client sending trigger kind `?COMPLETION_TRIGGER_KIND_FOR_INCOMPLETE_COMPLETIONS`.
Now erlang ls will handle it the same as `?COMPLETION_TRIGGER_KIND_INVOKED`
=> Treat incomplete trigger kind as invoked completion

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
This should fix the navigation issues described in the issue.
Fixes #1323 .
=> Consider argument of ifdef, ifndef, undef attributes to be a macro

apps/els_core/include/els_core.hrl, apps/els_core/src/els_client.erl, apps/els_core/src/els_provider.erl, apps/els_lsp/priv/code_navigation/src/signature_help.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_signature_help_provider.erl, apps/els_lsp/test/els_signature_help_SUITE.erl
Implements [signature help](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp) from the LSP spec.
For this PR it's just remote and local functions - BIFs, macros, or types aren't included yet.
The approach for finding the signature (if it exists) when a trigger is emitted is to scan backwards through the tokens that preceed the trigger and look for an unmatched opening parenthesis. Also in this recursive scanning function, we determine the active parameter number by counting the number of commas. It's not that straightforward though: you might have expressions in your calls that themselves contain commas like `maps:put(key, value, #{a => b, c => d})`. To count the active parameter number, we use a stack of counters …
=> Implement textDocument/signatureHelp

apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/test/els_definition_SUITE.erl
Summary:
https://github.com/erlang-ls/erlang_ls/issues/1205 suggested supporting the goto-definition feature for testcases.
Testcases are atoms (function definitions) and currently whenever doing goto-definition on an atom we treat it as a module.
I simply modified goto_definition to first look for a function of arity 1 in the current module when it is unclear whether the user is looking for a module or a testcase.
Test Plan:
I added the "testcase" test-case in els_definition_SUITE, following the structure of all other test-cases in that file.
This new testcase corresponds to doing "goto definition" on the atom "one" which appears in "all() -> [ one ]" in sample_SUITE.erl.
It verifies that we are sent to the definition of one at the bottom of sample_SUITE.erl.
I then checked that this new …
=> [#1205] Implement goto_definition for testcases.

apps/els_core/src/els_provider.erl, apps/els_lsp/src/els_call_hierarchy_provider.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_lens_provider.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_definition_provider.erl, apps/els_lsp/src/els_diagnostics_provider.erl, apps/els_lsp/src/els_document_highlight_provider.erl, apps/els_lsp/src/els_document_symbol_provider.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_folding_range_provider.erl, apps/els_lsp/src/els_formatting_provider.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_implementation_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/src/els_server.erl, apps/els_lsp/src/els_signature_help_provider.erl, apps/els_lsp/src/els_sup.erl, apps/els_lsp/src/els_text_synchronization_provider.erl, apps/els_lsp/src/els_workspace_symbol_provider.erl, apps/els_lsp/test/els_server_SUITE.erl, apps/els_lsp/test/prop_statem.erl
The els_provide process is a remain from the times where providers had
their own dedicated processes and it does not currently provide
additional value. It actually makes provider errors not bubble up to
the client. In fact, in case of a provider error the provider process
would crash, but the server would indefinitely wait for a
response. The error would not be returned via LSP.
This change simplifies the architecture of Erlang LS by merging the
els_server and els_provider processes:
* Get rid of els_provider process and internal_state
* Remove obsolete available_providers function
* Do not pass server state to providers
As a follow up, it should be possible to:
* Pass requests as-they-are (as opposed to only the parameters) to
providers, avoiding an un-necessary translation layer
* …
=> Merge server and provider processes.

apps/els_lsp/src/els_general_provider.erl
By being able to register capabilities dynamically, Erlang LS can
instruct the client to send `didChangeWatchedFiles`
requests whenever a file or directory is modified outside of the
client itself. Through this mechanism it is possible to prevent text
synchronization issues and crashes during events such as a rebase or a checkout.
=> Register capabilities dynamically, complete support for didChangedWatchedFiles

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_call_hierarchy_provider.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_lens_provider.erl, apps/els_lsp/src/els_definition_provider.erl, apps/els_lsp/src/els_diagnostics_provider.erl, apps/els_lsp/src/els_document_highlight_provider.erl, apps/els_lsp/src/els_document_symbol_provider.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_folding_range_provider.erl, apps/els_lsp/src/els_formatting_provider.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_implementation_provider.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/src/els_semantic_token_provider.erl, apps/els_lsp/src/els_signature_help_provider.erl, apps/els_lsp/src/els_workspace_symbol_provider.erl, apps/els_lsp/test/els_initialization_SUITE.erl, apps/els_lsp/test/els_initialization_SUITE_data/providers_custom.config, apps/els_lsp/test/els_initialization_SUITE_data/providers_invalid.config
Adds a configuration option `providers` with `enabled` and `disabled` lists. These can be used to configure which providers the language server should advertise to the client in the ServerCapabilities message. For example, to enable signature help:
```yaml
providers:
enabled:
- signature-help
```
This could also be useful to bring in #980 as disabled-by-default.
The implementation is mostly inspired by the `lenses` configuration option which takes the same shape.
Fixes #1310.
=> [#1310] Add a configuration option for advertised LSP providers.

apps/els_dap/src/els_dap_protocol.erl
The body field is required on most DAP Events and optional on Terminated but
is actually not included in Initialized at all. Clients parsing the Events
strictly will think an Initialized Event with a body is malformed, so this
change drops the field entirely for Initialized.
https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized
=> Do not send the 'body' field for DAP Initialized Event.

apps/els_dap/src/els_dap_general_provider.erl
There's a required `expensive` field on the Scope Type used
to hint to the client whether the variables in the given scope are
expensive to retrieve.
https://microsoft.github.io/debug-adapter-protocol/specification#Types_Scope
=> DAP: add `expensive` field to scopes type.

apps/els_lsp/src/els_compiler_diagnostics.erl
The `compile:file/1` function can return a relative path depending on
the directory the emulator is started on. This corner case was
resulting in occasional crashes for the users which prevented
diagnostics to appear if an included file contained errors.
=> Ensure to pass an absolute path to the `els_uri:uri/1` function

rebar.config
Temporarily remove eqwalizer as a project dependency, since the
git_subdir method breaks our internal upgrade scripts.
This does not affect eqwalizer diagnostics, which are still available.
=> Remove eqwalizer as dependency

apps/els_lsp/src/els_background_job.erl, apps/els_lsp/src/els_server.erl, apps/els_lsp/test/els_progress_SUITE.erl
If task is long running, the background job gen_server will not process messages meanwhile. So when stopping background job, it seems supervisor will timeout and kill the process instead of graceful shutdown. So terminate function is not called.
This PR changes to run the task in a subprocess.
Also send an error response for cancelled tasks. As I understand it, even cancelled requests must send a response.
Fixes https://github.com/erlang-ls/erlang_ls/issues/1365 .
=> Send end progress when request is cancelled.

apps/els_core/src/els_config_runtime.erl, apps/els_core/src/els_distribution_server.erl, apps/els_core/src/els_utils.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
When using `longnames` in projects that don't adhere to the host-provided hostname and domain it is useful to be able to override those via the `erlang_ls.config` file.  The code in this commit provides these options as well as cleans up some related duplicated code.
This code also fixes a small bug that would leave a trailing dot `.` if a domain is not defined.
Tests have been updated to reflect these changes and new tests have been created to test the new options.
A sample config file with the new options looks like this:
```yaml
apps_dirs:
- "src/*"
include_dirs:
- "src"
- "src/*/include"
code_reload:
node: "node1@127.0.0.1"
runtime:
use_long_names: true
hostname: "127"
domain: "0.0.1"
```
The above is an exaggerated example, a simple, more direct one that accomplishes the same would …
=> [1371] Add Custom Hostname and Domain Options

apps/els_dap/src/els_dap_breakpoints.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_rpc.erl, apps/els_dap/test/els_dap_general_provider_SUITE.erl
support non-verified breakpoints in case the module isn't available in the debugged node
Before this would crash, now create a non-verified breakpoint, with some description
Fixes #1373
=> [dap] support non-verified breakpoints 

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
Fix error when parsing record containing a comment.
Fixes #1290 .
=> [#1290] Fix error when parsing record containing a comment

apps/els_core/src/els_text.erl, apps/els_core/src/els_utils.erl, apps/els_lsp/priv/code_navigation/src/completion_records.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_scope.erl, apps/els_lsp/test/els_completion_SUITE.erl
Support completion of record fields inside #record{}
* Automatic triggering when cursor is at #record{| and #record{... , |
* Invoked completion on record field inside record #record{field|
Fixes #1360 .
=> [#1360] Support completion of record fields inside #record{}

apps/els_core/src/els_client.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_prepare_rename_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_initialization_SUITE.erl, apps/els_lsp/test/els_rename_SUITE.erl
Add support for prepareRename request
Fixes #1353.
=> [#1353] Add support for prepareRename request

apps/els_lsp/src/els_docs.erl, apps/els_lsp/test/els_hover_SUITE.erl
`els_docs:docs/2` was not previously implemented for `function_clause` and `spec` POIs, so hover requests would return `null` when hovering over function and spec definitions. This change returns the function definition docs for both cases.
The new behavior is in line with other language servers (ElixirLS, rust-analyzer) and can be useful - for example to see how the documentation looks for a function you're just written.
=> Show function docs for function_clauses and specs

apps/els_lsp/priv/code_navigation/src/implementation.erl, apps/els_lsp/src/els_implementation_provider.erl, apps/els_lsp/test/els_implementation_SUITE.erl
Add support for finding implementation when pointing to a dynamic call that is a behaviour callback.
=> Add support for finding callback implementation for dynamic calls

apps/els_lsp/priv/code_navigation/src/code_navigation_extra.erl, apps/els_lsp/priv/code_navigation/src/code_navigation_types.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/test/els_completion_SUITE.erl
Improve context awareness of completion
- Only relevant type completions should be suggested when in type context (such as `-spec`, `-type`, and type definition inside `-record`).
- Don't include args in completion when pointer is right before `(`
Fixes #1252.
=> Improve context awareness of completion

.git-blame-ignore-revs
Git allows ignore revisions from blame results with
git blame --ignore-revs-file .git-blame-ignore-revs
GitHub also allows ignoring revisions from blame results: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
This is usually used for large auto-formatting commits since the formatting changes are a bit noisy and can make it tricky to poke around the blame.
What do you think?
=> Ignore auto-formatting commit from git blame

apps/els_lsp/src/els_completion_provider.erl
Completion for fields in records (see #1381) currently sends only snippet syntax. This change checks if the client supports snippets and falls back to only providing the field name when the client does not support snippets.
=> Check snippet support in record field completion

apps/els_lsp/src/els_indexing.erl
Unused include diagnostic can hog the CPU if there's unreachable include files in combination with huge search path and large source files.
The issue boils down to calling `file:path_open/3` on the unreachable files for every POI in the source file.
To improve the performance memoization on error was added in `els_indexing:find_and_deeply_index_file/1` to avoid repeatedly calling `file:path_open/3` on the same filename.
=> Fix performance issue with unused include diagnostics

apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/test/els_code_action_SUITE.erl
Code action to add missing -behaviour callbacks.
=> Add code action to add behaviour callbacks

apps/els_lsp/src/els_docs.erl, apps/els_lsp/test/els_hover_SUITE.erl
This is a similar change as #1385: hovering definitions for types and opaques now shows the same documentation as hovering references. This is useful for checking how the hover will look to consumers of a type when writing docs.
=> Show type docs when hovering type definitions

apps/els_core/src/els_config.erl, apps/els_core/src/els_utils.erl
erlang-ls/erlang_ls#346 discarded any paths containing symlinks since they broke assumptions about there being a single URI for each module in calls to `els_utils:find_module/1`.
erlang-ls/erlang_ls#648 added prioritization for cases when there are multiple URIs in `els_utils:find_module/1`, so discarding paths with symlinks is now no longer necessary.
Following symlinks is necessary when using rebar3 checkout dependencies (erlang-ls/erlang_ls#1046) or when using Bazel (erlang-ls/erlang_ls#1064) since Bazel places dependencies and compiled files under its cache directory and symlinks the relevant directory in the cache to the workspace directory.
This change removes the behavior of `els_utils:resolve_paths/2` that discards paths containing symlinks.
I tested this in a rebar3 project with …
=> [#1046,#1064] Follow symlinks in `els_utils:resolve_paths/2`

apps/els_lsp/src/els_code_lens_suggest_spec.erl, apps/els_lsp/test/els_code_lens_SUITE.erl, apps/els_lsp/test/els_initialization_SUITE.erl
This lens often requires some manual configuration to work and it can be quite CPU intensive.
Disabling it by default to avoid noise for many users (eg when navigating to the OTP repository itself).
=> Disable suggest-spec lens by default

apps/els_lsp/src/els_code_actions.erl
In some corner cases, it can happen that the incoming request does not contain a `data` field, which defaults to `<<>>`.
That causes a server crash, since a Uri is expected.
=> Do not crash in case of empty data

apps/els_core/src/els_config.erl, apps/els_dap/src/els_dap_general_provider.erl, apps/els_lsp/src/els_general_provider.erl
Description
========
If the the configuration file(s) found cannot be parsed, show a notice for the user instead of silently moving on to the next config alternative.
Fixes  #1401
=> [#1401] Present configuration read errors for the user

.github/workflows/build.yml, apps/els_lsp/src/els_docs.erl, apps/els_lsp/test/els_completion_SUITE.erl, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/prop_statem.erl
Problem
======
The hover and completion provider test suites have some test cases for showing docs.
Some tests are testing the Erlang LS internal fallback docs provided if EEP-48 docs can not be extracted. These test cases don't work with newer OTP versions (because their expected values depend on the EEP-48 docs not being available).
Some of the tests are testing edoc extraction itself, and have conditional expectations depending on if EEP-48 docs are available or not. These tests assume that OTP >= 24 will always have EEP-48 docs for `file:write` if `code:get_docs(file)` is not empty, but this is not the case (see e.g. https://github.com/erlang-ls/erlang_ls/pull/1402#discussion_r1020932452). The test suites and the code in els_docs are not in agreement about when the docs are available. …
=> Make test suite work in OTP 25

apps/els_dap/src/els_dap_general_provider.erl, apps/els_dap/src/els_dap_rpc.erl, apps/els_dap/test/els_dap_general_provider_SUITE.erl, elvis.config
This is a workaround for [a bug in the OTP interpreter](https://github.com/erlang/otp/issues/7336), which causes breakpoints to stay active, even after they are removed by the user via the UI, for existing processes.
This makes removing breakpoints a very confusing experience, especially in presence of recursive functions, where the only option left to the user is to interrupt and restart the debugging session.
In this PR:
* Created a test-case which highlights the issue (the test would time out before the fix)
* Ensure the breakpoints are purged on a new `setBreakpoints` call
* Add helper function to wait for processes to resume regular operation
=> [DAP] Ensure breakpoints are purged on setBreakpoints

rebar.config, rebar.lock
This version of Gradualizer brings approx. 30 PRs. The highlights are:
- Improve map exhaustiveness checking [#524](https://github.com/josefs/gradualizer/pull/524) by @xxdavid
- Fix all remaining self-check errors [#521](https://github.com/josefs/gradualizer/pull/521) by @erszcz
- Fix intersection-typed function calls with union-typed arguments [#514](https://github.com/josefs/gradualizer/pull/514) by @erszcz
- Experimental constraint solver [#450](https://github.com/josefs/gradualizer/pull/450) by @erszcz
=> Update Gradualizer to 0.3.0

specs/runtime_node.md
typo: `erlang_ls.comfig` -> `erlang_ls.config`
=> [typo] Update runtime_node.md

apps/els_lsp/src/els_compiler_diagnostics.erl
This pull request adds support for parsing extended "head mismatch" errors as introduced in https://github.com/erlang/otp/pull/7383.
=> Handle extended head mismatch error

.github/workflows/release.yml
So they can be downloaded by external clients, such as lsp-erlang.
See https://github.com/erlang-ls/erlang_ls/actions/runs/5762933437 for a successful run, and
https://github.com/erlang-ls/erlang_ls/releases/tag/0.48.1-test3 for the release with artefacts.
=> Add github release.yml to publish binary artifacts

apps/els_core/src/els_dodger.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_definition_provider.erl, apps/els_lsp/test/els_definition_SUITE.erl
Currently `erlang_ls` supports navigation from a behaviour callback to its implementation. It is not possible to navigate back from the implementation to the definition to the callback using goto definition. This PR adds this support.
Looking forward hearing some feedback on this. Have a nice day!
=> Add goto definition for implemented behaviour callbacks

apps/els_core/src/els_config.erl, apps/els_core/src/els_dodger.erl, apps/els_lsp/src/els_docs.erl
Adds config option to disable edoc parsing.
Found that parsing some files took very long time to edoc parse which made completion break.
Simple solution, add an option to disable the edoc parsing if one runs into such issues.
For future consideration: Add a timeout for edoc parsing so it can be interrupted if it takes too long.
=> Add edoc_parse_enabled to config

apps/els_core/src/els_uri.erl, rebar.config
`els_uri:path/2` was calling `uri_string:percent_decode/1`, which is unavailable until OTP 23.2
(https://www.erlang.org/doc/man/uri_string#percent_decode-1)
=> [LSP] Fix initialize on OTP 23.0/23.1

apps/els_lsp/src/els_completion_provider.erl
Added types were introduced in OTP24, but since macro FEATURE_AVAILABLE (introduced in OTP25) is available, I think those types should be too.
=> added nonempty_binary and nonempty_bitstring

apps/els_core/src/els_config.erl, erlang_ls.config.sample
I am currently maintaining a project whose 'erl' files is not in the 'src' directory.
In order for the plugin to work properly on my project, a new configuration item was added so that directories other than 'src' could be included in the source code search.
=> Added config item 'erls_dirs' to add code not in 'src' to the scope

apps/els_lsp/priv/code_navigation/src/variable_list_comp.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_definition_SUITE.erl, apps/els_lsp/test/els_rename_SUITE.erl
Make goto variable definition respect list comprehension scopes.
Fixes #1337 .
=> [#1337] Make goto variable definition respect list comprehension scopes

apps/els_lsp/src/els_typer.erl
OTP26 added the `dialyzer_iplt` module and took over some of the PLT functions from `dialyzer_plt`. I added some conditional compilation to use the dialyzer_iplt functions on 26+ and dialyzer_plt on 25-. `dialyzer_iplt` comes from the big refactor for incremental mode: https://www.erlang.org/blog/otp-26-highlights/#incremental-mode-for-dialyzer
Fixes #1443.
=> els_typer: Handle OTP26 changes to dialyzer functions

apps/els_core/src/els_uri.erl
If a LSP client on Windows sends a capital drive letter in a URI, then the compiler diagnostics end up sending the wrong position/range. 
This is because of [this line.](https://github.com/erlang-ls/erlang_ls/blob/e91c9519996e0ff701edc19f308524906a3df131/apps/els_lsp/src/els_compiler_diagnostics.erl#L195) It checks that the path from the compiler matches the URI path. The path from the compiler has a lowercase drive letter, so they don't match and the diagnostics are treated as if they are coming from an include.
I've fixed this in els_uri:path, but there might be a better place to do it, I'm not sure.
=> Lowercase drive letter in URIs for Windows

apps/els_core/src/els_utils.erl
The plugin starts with 'index_dir/4' and 'shallow_index/4' for every file retrieved, but its search level is shallow and there is no way to cover the source code in the subdirectory. This commit aims to solve this problem.
=> 'index_dir' cover the source code in the subdirectory

apps/els_lsp/src/els_unused_includes_diagnostics.erl
normally, include another `.hrl` in an `.hrl` file, don't have to warning unuse in this situation.
a.hrl
```
-include("aa.hrl").
-include("aaa.hrl").
```
a.erl
```
-include("a.hrl").
```
=> Idea: hrl don't have to warning unuse

apps/els_lsp/src/els_code_reload.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_text_synchronization_provider.erl, apps/els_lsp/test/els_code_reload_SUITE.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
See #1409 for background. Given that hot-reloading from an editor is a development feature it should not matter if there are diagnostic errors while iterating.
The reason I moved the code out from `els_compiler_diagnostics` is that it seemed a bit misplaced in there and looking at commit history it looks like code reload was added before the `els_diagnostics` behavior existed, and it was just inside `els_text_synchronization_provider`. If it is to be detached from diagnostics results it seems there is little reason to keep it in `els_compiler_diagnostics`.
Fixes #1409 
Stop trying to compile and reload files that are not ".erl" files. It doesn't work and just gives popup spam.
The moved test cases work fine. I also manually tested that code reloading still works.
If the remote node has a …
=> Make code_reload act regardless of diagnostics

apps/els_core/src/els_utils.erl
This might be helpful in situations when tooling (e.g. `rebar3`) makes "shadow copies" in the indexable project directories. This might happen when underlying filesystem lacks sound symlink support, or (in my case) when slightly patched `rebar3` is used.
Before this change files having `_build/` in filepath were preferred over those having `apps/` or `src/` for example.
=> Respect appdirs when prioritizing module candidates

apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_text_search.erl, apps/els_lsp/test/els_references_SUITE.erl
This change indexes atoms in the references table and adds support for finding atoms in the references provider.
=> Find references for atoms

rebar.config
We saw situations where erlang_ls interfered with the application being developed through `global`. We had a locking issue that only occurred when the editor with erlang_ls was running. Adding `-hidden` resolves the problem for us.
=> Add -hidden flag

apps/els_lsp/priv/code_navigation/src/diagnostics_xref_pseudo.erl, apps/els_lsp/src/els_crossref_diagnostics.erl
=> Fix invalid crossref warning for Mod:module_info()

apps/els_core/src/els_config.erl, apps/els_lsp/priv/code_navigation/src/docs_memo.erl, apps/els_lsp/src/els_db.erl, apps/els_lsp/src/els_docs.erl, apps/els_lsp/src/els_docs_memo.erl, apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_text_synchronization.erl, apps/els_lsp/test/els_docs_SUITE.erl, apps/els_lsp/test/els_docs_SUITE_data/docs_memo_false.config, apps/els_lsp/test/els_docs_SUITE_data/docs_memo_true.config, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/els_hover_SUITE_data/docs_memo_true.config
Closes #1208, and a little more. Since the memoization is done in `els_docs`, the change should also help `els_signature_help_provider` and `els_completion_provider`. Should tests be written here for the integration with the 2?
Also, there is a slight difference between this PR and #1208 in that there is a small amount of time when the memoization can be cancelled. I wasn't able to think of a solution without changing `els_background_job`.
=> Add docs memoization

apps/els_lsp/src/els_code_reload.erl
Hi. When working on clustered applications (RabbitMQ in my case), it's useful to reload the code on all nodes in the cluster. Otherwise I can't really use reloading since I still need to restart the other nodes to pick up the changes. This is a very rudimentary change that gets the job done for me (I've been happily using it for a few days). Would you accept something like that?
I decided to "overload" the `code_reload.node` setting and allow it to be a list. Alternatively, we could have a separate field (`code_reload.nodes`) but then we would need to handle both being set for example. I'm happy to make such changes if you prefer.
Thanks,
=> Allow `code_reload.node` to be a list of nodes

apps/els_core/src/els_config.erl, apps/els_lsp/src/els_formatting_provider.erl
The low-level formatting plugin erlang_ls relies on supports some formatters, maybe it would be good to expose them into the configuration.
This PR added a new configuration section with an option to specify the formatter
Fixes # .
=> Allows custom setting the formatter

apps/els_core/src/els_config.erl
Logging root path could be useful when debugging indexing issues
=> Log root path when initializing

apps/els_core/src/els_text.erl
This is not really a proper fix since it will make text editing less efficient, but finding the root cause is tricky.
A follow up change could be made to fix the root cause.
Fixes #1427.
=> Multiple edits could cause invalid text edits

apps/els_lsp/priv/code_navigation/src/diagnostics_behaviour_recursive.erl, apps/els_lsp/priv/code_navigation/src/diagnostics_behaviour_recursive_impl.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_diagnostics_utils.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
=> Handle recursive deps for behaviours

apps/els_core/src/els_utils.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/src/els_text_search.erl, elvis.config
Improve performance of looking up references to macros/records.
Finding scoped references can be done in two ways:
* Naive, find all POIs that can reach our POI and matches the id.
* Indexed, use the index to find all matching POIs, then check if
they actually reference our POI by using goto_definition.
It varies from case to case which is the fastest, so we race both
functions to get the quickest answer.
Fixes #1309.
=> Improve macro refs performance

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
Erlfmt will skip parsing if it finds pragma `@noformat` in the text. In order to trick erlfmt to parse the file we replace `@noformat` with `@doformat` if we it tries to skip the parsing.
Fixes #1482.
=> Fix els_parser crash due to erlfmt returning {skip, _}

apps/els_lsp/src/els_docs.erl
Doc chunk generation can be very slow, this would cause completion to hang until finished. 
Instead we now spawn a process and return after 1 second if it generation hasn't completed.
Add check to only generate doc chunks if the chunk file is missing or not up to date.
=> Run edoc chunk generation in spawned process

apps/els_lsp/priv/code_navigation/src/code_action.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_code_action_SUITE.erl
The create function code action will now use the argument names used in the function call.
It will also try to indent correctly by guessing indentation amount by analyzing the source file.
=> Improve create function code action

apps/els_lsp/src/els_completion_provider.erl
Sometimes is_in will be confused because -export() failed to be parsed. 
In such case we can use a heuristic to determine if we are inside an export.
Fixes #1488 .
=> Add heuristic to improve completion in exports.

apps/els_core/src/els_config.erl
If we find a `rebar.config` file (and no `erlang.mk`!) we will use rebar3's directory structure as defaults for `deps_dirs`, `apps_dirs` and `include_dirs`. 
Note that this is just defaults, so they will be overridden if there is an `erlang_ls.config` file either locally or globally.
This will hopefully improve the experience for new users when jumping into a rebar3 project.
=> Add some sensible defaults if rebar.config is found

apps/els_lsp/src/els_text_edit.erl
Fix garbled output when formatting unicode characters
This happened due to applying `unicode:characters_to_binary` on a list that contains bytes, not code points.
Fixes #1236, #1494.
=> Fix garbled output when formatting unicode characters

apps/els_lsp/priv/code_navigation/include/builtin_macros.hrl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
Don't emit parser error when ?MODULE is used in a header file.
Fixes #1498.
=> Don't emit parser error when ?MODULE is used in a header file

apps/els_core/include/els_core.hrl, apps/els_core/src/els_client.erl, apps/els_core/src/els_config.erl, apps/els_lsp/priv/code_navigation/src/inlay_hint.erl, apps/els_lsp/src/els_arg.erl, apps/els_lsp/src/els_background_job.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_code_lens_provider.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_diagnostics_provider.erl, apps/els_lsp/src/els_docs.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_general_provider.erl, apps/els_lsp/src/els_hover_provider.erl, apps/els_lsp/src/els_inlay_hint_provider.erl, apps/els_lsp/src/els_methods.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_server.erl, apps/els_lsp/src/els_signature_help_provider.erl, apps/els_lsp/test/els_call_hierarchy_SUITE.erl, apps/els_lsp/test/els_inlay_hint_SUITE.erl
Argument names in function calls will now show up as inlay hints.
Inlay hints are disabled by default, enable by adding this to config:
inlay_hints_enabled: true
Additional changes:
* Add functional API to submit job results to els_server (Fixes #1334)
* Improve completions by extracting argument names from spec.
* Improve completions by extracting argument names from all function clauses.
* Gracefully handle parsing of missing header file
=> Add support for inlay hints

apps/els_core/src/els_poi.erl, apps/els_core/src/els_utils.erl, apps/els_lsp/priv/code_navigation/src/extract_function.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_document_highlight_provider.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_code_action_SUITE.erl, apps/els_lsp/test/els_execute_command_SUITE.erl, apps/els_lsp/test/els_workspace_symbol_SUITE.erl
Add refactoring code action to extract function
=> Add refactoring code action to extract function

apps/els_lsp/src/els_implementation_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
Add support for parsing implicit fun with ?MODULE
Also add support for parsing variables in implicit funs.
Fixes #726 .
=> Add support for parsing implicit fun with ?MODULE

.github/workflows/build.yml, .github/workflows/release.yml, README.md, apps/els_lsp/test/els_formatter_SUITE.erl, apps/els_lsp/test/els_hover_SUITE.erl, apps/els_lsp/test/els_text_edit_SUITE.erl
With OTP 27 around the corner, it's time to drop OTP 23 support.
NOTE: 
Some CT tests started failing on Windows, these have been disabled and needs to be fixed.
=> Drop OTP 23 support

apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/src/els_text_synchronization.erl
Small fix to make a small performance improvement when opening a file the first time.
Avoids running get_words twice from did_open, and also makes the set created in get_words use version 2 which is a bit more efficient, supported from OTP24.
On a big file like erlfmt_parse.erl on my computer the time spent went from about 960ms to ~850ms.
=> Avoid running get_words twice when opening new file

misc/dotemacs
link-mode no longer supported and replaced by a built in functionality.
Fixes #1514
=> Change linum-mode to display-line-numbers-mode

apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_parser_SUITE.erl
Partial support for this was already added in the inlay hints PR.
Now we also support extracting argument names from specs of this format:
```
-spec member(Elem, List) -> boolean() when
Elem :: T,
List :: [T],
T :: term().
```
Fixes #1362 .
=> Extract argument names from specs

apps/els_lsp/src/els_inlay_hint_provider.erl, apps/els_lsp/test/els_inlay_hint_SUITE.erl
Each function clause of an exported function is now prefixed by an inlay hint "exp".
=> Add inlay hints to show if a function is exported

apps/els_lsp/src/els_code_reload.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/src/els_eunit_diagnostics.erl, apps/els_lsp/src/els_eunit_listener.erl, apps/els_lsp/test/els_code_reload_SUITE.erl, rebar.config
Disabled by default.
Requires a running `code_reload` node.
=> Add support for eunit diagnostics

apps/els_lsp/src/els_code_reload.erl
Handle {d, 'TEST'} format when recompiling.
=> Add 'TEST' macro to options when compile for reload

apps/els_core/src/els_poi.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_compiler_diagnostics.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/src/els_crossref_diagnostics.erl, apps/els_lsp/src/els_docs.erl, apps/els_lsp/src/els_document_highlight_provider.erl, apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/src/els_range.erl, apps/els_lsp/src/els_references_provider.erl, apps/els_lsp/src/els_rename_provider.erl, apps/els_lsp/test/els_completion_SUITE.erl
Adds completion for [-nifs attribute](https://www.erlang.org/doc/reference_manual/modules#pre-defined-module-attributes) officially supported from OTP25
=> nifs attribute completion

apps/els_core/src/els_text.erl, apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_definition_provider.erl
Use tokens to generate POIs on lines where parsing fails. 
Currently handling call(), module:call(), ?MACRO, #record, atom.
=> Go to definition can now handle lines where parsing fails

.github/workflows/build.yml, .github/workflows/release.yml, apps/els_lsp/test/els_diagnostics_SUITE.erl
Add workflows to build and release on macos.
=> Workflows macos

apps/els_lsp/priv/code_navigation/src/completion_records.erl, apps/els_lsp/src/els_completion_provider.erl, apps/els_lsp/test/els_completion_SUITE.erl
Fix bug where completion would erroneously think it's inside a record
=> Fix bug where completion would erroneously think it's inside a record

apps/els_lsp/src/els_formatting_provider.erl, apps/els_lsp/test/els_formatter_SUITE.erl
This will make document formatting use the unsaved state of the file.
Fixes #1419  .
=> Make formatting use in-memory text instead of file content.

apps/els_lsp/priv/code_navigation/src/diagnostics_xref_pseudo.erl, apps/els_lsp/src/els_crossref_diagnostics.erl, apps/els_lsp/src/els_db.erl, apps/els_lsp/src/els_diagnostics.erl, apps/els_lsp/src/els_dt_functions.erl, apps/els_lsp/src/els_indexing.erl, apps/els_lsp/test/els_diagnostics_SUITE.erl
* Don't run diagnostics unless indexing is done
* Improve performance of crossref diagnostics
* Remove incorrect warnings for lager:debug_unsafe/2 and lists:append/1 
Fixes #1410 .
=> Improve performance of crossref diagnostics.

apps/els_lsp/src/els_inlay_hint_provider.erl
=> Don't show inlay hint for _Var if arg is named Var

apps/els_lsp/src/els_code_navigation.erl, apps/els_lsp/src/els_definition_provider.erl
If we don't have a precise match, try to find a close match for goto definition, e.g. if we have a(q,w,e) but only a/4 defined jump there.
Fixes #1250 .
=> Fuzzy goto

apps/els_lsp/src/els_code_actions.erl
=> Fix crash in code actions

apps/els_core/src/els_poi.erl, apps/els_core/src/els_text.erl, apps/els_lsp/priv/code_navigation/src/extract_function.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_dt_document.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/src/els_parser.erl, apps/els_lsp/test/els_code_action_SUITE.erl, apps/els_lsp/test/els_execute_command_SUITE.erl
* Ignore variables inside funs() and list comprehensions
* Don't suggest to extract function unless it contains more than one poi
=> Improvements to extract function

apps/els_core/include/els_core.hrl, apps/els_core/src/els_config.erl, apps/els_core/src/els_uri.erl, apps/els_lsp/priv/code_navigation/src/code_action_browse_docs.erl, apps/els_lsp/src/els_code_action_provider.erl, apps/els_lsp/src/els_code_actions.erl, apps/els_lsp/src/els_dt_references.erl, apps/els_lsp/src/els_execute_command_provider.erl, apps/els_lsp/test/els_code_action_SUITE.erl, apps/els_lsp/test/els_completion_SUITE.erl, elvis.config
* Browse elvis warnings
* Browse compiler errors
* Browse functions and types in otp docs or hex docs
=> Introduce browse code actions
